

package com.idcos.enterprise.portal.dal.repository;

// auto generated imports

import com.idcos.cloud.core.dal.common.jpa.BaseRepository;
import com.idcos.enterprise.portal.dal.entity.PortalRole;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

/**
 * 自动生成PortalRoleRepository
 * <p>
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2015-09-15 09:22:12.
 *
 * @author yanlv
 * @version PortalRoleRepository.java, v 1.1 2015-09-15 09:22:12 yanlv Exp $
 */
public interface PortalRoleRepository extends BaseRepository<PortalRole, String> {

    /**
     * <p>
     * The jql statement for this operation is <br>
     *
     * @param code
     * @param isActive
     * @return List<PortalRole>
     */
    List<PortalRole> findByCodeAndIsActive(String code, String isActive);

    /**
     * <p>
     * The jql statement for this operation is <br>
     *
     * @param isActive
     * @return List<PortalRole>
     */
    List<PortalRole> findByIsActive(String isActive);

    /**
     * <p>
     * The jql statement for this operation is <br>
     * <tt>select r from PortalRole r where r.isActive='Y' order by r.name</tt>
     *
     * @return List<PortalRole>
     */
    @Query("select r from PortalRole r where r.isActive='Y' order by r.name")
    List<PortalRole> queryRoleList();

    /**
     * findRolePageByGroupIdAndCnd
     *
     * @param groupId
     * @param cnd
     * @return
     */
    @Query("select distinct u from PortalRole u,PortalGroupRoleRel r where u.id=r.roleId and r.groupId =?1 and u.isActive='Y' and (u.name like ?2 or u.code like ?2 or u.remark like ?2)")
    List<PortalRole> findRolePageByGroupIdAndCnd(String groupId, String cnd);
}