

package com.idcos.enterprise.portal.dal.repository;

// auto generated imports

import com.idcos.cloud.core.dal.common.jpa.BaseRepository;
import com.idcos.enterprise.portal.dal.entity.PortalUser;
import org.springframework.data.jpa.repository.Query;

import java.util.Date;
import java.util.List;

/**
 * 自动生成PortalUserRepository
 * <p>
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2015-09-15 09:22:12.
 *
 * @author yanlv
 * @version PortalUserRepository.java, v 1.1 2015-09-15 09:22:12 yanlv Exp $
 */
public interface PortalUserRepository extends BaseRepository<PortalUser, String> {
    /**
     * 模糊查询用户（姓名、登录名），根据GroupId
     *
     * @param id
     * @param cnd
     * @return
     */
    @Query("select u from PortalUser u,PortalGroupUserRel r where u.id = r.userId and r.groupId = ?1 and u.isActive='Y' and (u.name like ?2 or u.loginId like ?2)")
    List<PortalUser> findUserPageByGroupIdAndCnd(String id, String cnd);

    /**
     * 模糊查询用户（姓名、登录名）
     *
     * @param tenantId
     * @param cnd
     * @return
     */
    @Query("select u from PortalUser u where u.tenantId=?1 and u.isActive='Y' and (u.name like ?2 or u.loginId like ?2)")
    List<PortalUser> queryUserByCnd(String tenantId, String cnd);

    /**
     * 根据tenantId和deptId集合查询用户
     *
     * @param tenantId
     * @param ids
     * @return
     */
    @Query("select u from PortalUser u where u.tenantId = ?1 and u.deptId in ?2 and u.isActive = 'Y'")
    List<PortalUser> findPortalUserByDeptIdIn(String tenantId, List<String> ids);

    /**
     * 根据部门id查询用户
     *
     * @param deptId
     * @return
     */
    @Query("select u from PortalUser u where u.deptId = ?1 and u.isActive = 'Y'")
    List<PortalUser> findByDeptId(String deptId);

    /**
     * 查询所有用户
     *
     * @return
     */
    @Query("select u from PortalUser u where u.isActive = 'Y'")
    List<PortalUser> findIsActive();


    /**
     * getSyncByDept
     *
     * @param deptId
     * @param sourceType
     * @return
     */
    @Query("select u from PortalUser u where u.deptId=?1 and u.sourceType=?2")
    List<PortalUser> getSyncByDept(String deptId, String sourceType);

    /**
     * findAllSyncDept
     *
     * @param sourceType
     * @return
     */
    @Query("select u from PortalUser u where u.sourceType =?1 and u.isActive = 'Y'")
    List<PortalUser> findAllSyncUser(String sourceType);

    /**
     * 查询租户下的所有用户
     *
     * @param tenantId
     * @return
     */
    @Query("select u from PortalUser u where u.tenantId=?1 and u.isActive = 'Y'")
    List<PortalUser> findByTenantId(String tenantId);

    /**
     * 根据id查询用户
     *
     * @param userId
     * @return
     */
    @Query("select u from PortalUser u where u.id = ?1 and u.isActive = 'Y'")
    PortalUser findById(String userId);

    /**
     * 根据loginId查询用户
     *
     * @param tenantId
     * @param id
     * @return
     */
    @Query("select u from PortalUser u where u.tenantId = ?1 and u.loginId = ?2 and u.isActive = 'Y'")
    PortalUser findPortalUserById(String tenantId, String id);

    /**
     * 根据tenantId和id查询用户
     *
     * @param tenantId
     * @param id
     * @return
     */
    @Query("select u from PortalUser u where u.tenantId = ?1 and u.id = ?2 and u.isActive = 'Y'")
    PortalUser findPortalUserByAccountId(String tenantId, String id);

    /**
     * 根据tenantId和登录名List查询用户
     *
     * @param tenantId
     * @param accountNoList
     * @return
     */
    @Query("select u from PortalUser u where u.tenantId = ?1 and u.loginId in ?2 and u.isActive = 'Y'")
    List<PortalUser> findUserByIds(String tenantId, List<String> accountNoList);

    /**
     * 获取最后登录时间
     *
     * @return
     */
    @Query(nativeQuery = true, value = "SELECT u.LAST_LOGIN_TIME FROM PORTAL_USER u ORDER BY u.LAST_LOGIN_TIME DESC LIMIT 1")
    Date getLastLoginTime();

    /**
     * 查询租户下系统的帐号总数
     *
     * @param tenantId
     * @return
     */
    @Query("select count (u) from PortalUser u where u.tenantId = ?1 and u.isActive = 'Y'")
    Long getAccountCount(String tenantId);

    /**
     * 查询系统的帐号总数
     *
     * @return
     */
    @Query("select count (u) from PortalUser u where u.isActive = 'Y'")
    Long getAccountCount();
}
