

package com.idcos.enterprise.portal.dal.repository;

// auto generated imports

import org.springframework.data.jpa.repository.Query;

import com.idcos.cloud.core.dal.common.jpa.BaseRepository;
import com.idcos.enterprise.portal.dal.entity.PortalSysDict;

import java.util.List;

/**
 * 自动生成PortalRoleRepository
 * <p>
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2017-09-26 09:22:12.
 *
 * @author GuanBin
 * @version PortalRoleRepository.java, v 1.1 2017-09-26 09:22:12 yanlv Exp $
 */
public interface PortalSysDictRepository extends BaseRepository<PortalSysDict, String> {
    /**
     * 获取字典表用户组类型
     *
     * @param tenantId
     * @return
     */
    @Query("select sd.code from PortalSysDict sd where sd.typeCode = 'userGroupType' and sd.tenantId=?1")
    List<String> getUserGroupType(String tenantId);

    /**
     * 获取字典表用户组类型
     *
     * @param tenantId
     * @return
     */
    @Query("select sd from PortalSysDict sd where sd.typeCode = 'userGroupType' and sd.tenantId=?1")
    List<PortalSysDict> getUserGroupTypeAndValue(String tenantId);

    /**
     * 获取字典表用户状态
     *
     * @return
     */
    @Query("select sd from PortalSysDict sd where sd.typeCode ='userStatus'  and sd.tenantId='default'")
    List<PortalSysDict> getUserStatus();
}