

package com.idcos.enterprise.portal.dal.repository;

// auto generated imports

import com.idcos.cloud.core.dal.common.jpa.BaseRepository;
import com.idcos.enterprise.portal.dal.entity.PortalResource;

import java.util.List;

/**
 * 自动生成PortalResourceRepository
 * <p>
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2015-11-07 10:08:49.
 *
 * @author pengganyu
 * @version PortalResourceRepository.java, v 1.1 2015-11-07 10:08:49 pengganyu Exp $
 */
public interface PortalResourceRepository extends BaseRepository<PortalResource, String> {

    /**
     * 根据权限资源类型编码和有效标志查询权限资源类型信息
     *
     * @param code     权限资源类型编码
     * @param isActive 有效标志，Y/N
     * @return PortalResource 权限资源类型
     */
    public PortalResource findByCodeAndIsActive(String code, String isActive);

    /**
     * 查询全部权限资源类型
     *
     * @param isActive
     * @return
     */
    public List<PortalResource> findByIsActive(String isActive);

}