

package com.idcos.enterprise.portal.dal.repository;

// auto generated imports

import com.idcos.cloud.core.dal.common.jpa.BaseRepository;
import com.idcos.enterprise.portal.dal.entity.PortalDept;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

/**
 * 自动生成PortalRoleRepository
 * <p>
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2017-09-26 09:22:12.
 *
 * @author GuanBin
 * @version PortalRoleRepository.java, v 1.1 2017-09-26 09:22:12 yanlv Exp $
 */
public interface PortalDeptRepository extends BaseRepository<PortalDept, String> {
    /**
     * findAllDeptByTenantId
     *
     * @param tenantId
     * @return
     */
    @Query("select u from PortalDept u where u.tenantId = ?1 and u.status = '1'")
    List<PortalDept> findAllDeptByTenantId(String tenantId);

    /**
     * findAllByIsActive
     *
     * @return
     */
    @Query("select u from PortalDept u where u.status = '1'")
    List<PortalDept> findAllByIsActive();

    /**
     * findAllSyncDept
     *
     * @param sourceType
     * @return
     */
    @Query("select u from PortalDept u where u.sourceType =?1 and u.status ='1'")
    List<PortalDept> findAllSyncDept(String sourceType);

    /**
     * findByDeptId
     *
     * @param id
     * @return
     */
    @Query("select d from PortalDept d where d.id = ?1 and d.status = '1'")
    PortalDept findByDeptId(String id);

    /**
     * findByParentId
     *
     * @param id
     * @return
     */
    @Query("select dept from PortalDept dept where dept.parentId= ?1 and dept.status = '1'")
    List<PortalDept> findByParentId(String id);

    /**
     * 根据部门名称、tenantId和parentId查询部门
     *
     * @param displayName
     * @param tenantId
     * @param parentId
     * @return
     */
    @Query("select dept from PortalDept dept where dept.displayName=?1 and dept.tenantId=?2 and dept.parentId =?3 and dept.status = '1'")
    PortalDept findByDeptNameAndParentIdAndTenantId(String displayName, String tenantId, String parentId);

    /**
     * 根据部门名称、tenantId和parentId为空查询部门
     *
     * @param displayName
     * @param tenantId
     * @return
     */
    @Query("select dept from PortalDept dept where dept.displayName=?1 and dept.tenantId=?2 and dept.status = '1' and (dept.parentId is null or dept.parentId='')")
    PortalDept findByDeptNameAndTenantId(String displayName, String tenantId);

}