

package com.idcos.enterprise.portal.manager.auto;

// auto generated imports

import com.idcos.cloud.core.common.biz.CommonResult;
import com.idcos.enterprise.portal.dal.entity.PortalTenant;
import com.idcos.enterprise.portal.dal.entity.PortalUser;
import com.idcos.enterprise.portal.form.LoginForm;

/**
 * manager层controller相关的接口自动生成，此文件属于自动生成的，请勿直接修改,具体可以参考codegen工程
 * Generated by <tt>controller-codegen</tt> on 2015-11-07 16:44:40.
 *
 * @author jiaohuizhe
 * @version PortalUserQueryManager.java, v 1.1 2015-11-07 16:44:40 jiaohuizhe Exp $
 */
public interface AuthManager {

    /**
     * 验证登录信息
     *
     * @param loginForm
     * @return
     */
    String getAuth(LoginForm loginForm);

    /**
     * post方式创建token
     *
     * @param loginId
     * @param password
     * @param tenantId
     * @param time
     * @return
     */
    CommonResult<?> grantToken(String loginId, String password, String tenantId, String time);

    /**
     * post方式创建token
     *
     * @param loginId
     * @param tenantId
     * @return
     */
    CommonResult<?> grantTokenByAdmin(String loginId, String tenantId);

    /**
     * 分析token
     *
     * @param token
     * @return
     */
    CommonResult<?> parseToken(String token);

    /**
     * 修改盐
     *
     * @return
     */
    CommonResult<?> modifySalt();
}