

package com.idcos.enterprise.portal.manager.auto;

// auto generated imports

import com.idcos.cloud.core.common.biz.CommonResult;
import com.idcos.enterprise.portal.form.PortalPermissionSaveAuthObjForm;
import com.idcos.enterprise.portal.form.PortalPermissionSaveAuthResForm;

import java.util.List;

/**
 * manager层controller相关的接口自动生成，此文件属于自动生成的，请勿直接修改,具体可以参考codegen工程
 * Generated by <tt>controller-codegen</tt> on 2015-06-09 10:00:37.
 *
 * @author yanlv
 * @version PortalPermissionOperateManager.java, v 1.1 2015-06-09 10:00:37 yanlv Exp $
 */
public interface PortalPermissionOperateManager {

    /**
     * 保存授权对象关系
     *
     * @param form
     * @return ${method.returnType}
     */
    CommonResult<?> saveAuthObj(PortalPermissionSaveAuthObjForm form);

    /**
     * 保存授权资源关系
     *
     * @param permissionInfo
     * @return ${method.returnType}
     */
    CommonResult<?> saveAuthRes(String permissionInfo);

    /**
     * 绑定角色code和权限资源
     *
     * @param tenantId
     * @param roleCode
     * @param perList
     * @return
     */
    CommonResult<?> assignByRoleCode(String tenantId, String roleCode, List<PortalPermissionSaveAuthResForm> perList);

}
