

package com.idcos.enterprise.portal.manager.auto;

// auto generated imports

import com.idcos.cloud.core.common.biz.CommonResult;

/**
 * manager层controller相关的接口自动生成，此文件属于自动生成的，请勿直接修改,具体可以参考codegen工程
 * Generated by <tt>controller-codegen</tt> on 2015-08-21 10:22:49.
 *
 * @author yanlv
 * @version PortalCommonQueryManager.java, v 1.1 2015-08-21 10:22:49 yanlv Exp $
 */
public interface PortalCommonQueryManager {

    /**
     * 获取所有角色信息
     *
     * @return BaseResultVO
     */
    CommonResult<?> getRoleList();

    /**
     * 获取所有用户组信息
     *
     * @param tenantId
     * @return BaseResultVO
     */
    CommonResult<?> getUserGroupList(String tenantId);

}