

package com.idcos.enterprise.portal.manager.auto;

// auto generated imports

import com.idcos.cloud.core.common.biz.CommonResult;
import com.idcos.enterprise.portal.form.PortalPermissionQueryAuthObjForm;
import com.idcos.enterprise.portal.form.PortalPermissionQueryAuthResForm;

/**
 * manager层controller相关的接口自动生成，此文件属于自动生成的，请勿直接修改,具体可以参考codegen工程
 * Generated by <tt>controller-codegen</tt> on 2015-06-09 10:00:37.
 *
 * @author yanlv
 * @version PortalPermissionQueryManager.java, v 1.1 2015-06-09 10:00:37 yanlv Exp $
 */
public interface PortalPermissionQueryManager {


    /**
     * 获取授权对象ID
     *
     * @param form
     * @return ${method.returnType}
     */
    public CommonResult<?> queryAuthObj(PortalPermissionQueryAuthObjForm form);


    /**
     * 获取授权资源ID
     *
     * @param form
     * @return ${method.returnType}
     */
    public CommonResult<?> queryAuthRes(PortalPermissionQueryAuthResForm form);


}