

package com.idcos.enterprise.portal.manager.auto;

// auto generated imports

import com.idcos.cloud.core.common.biz.CommonResult;
import com.idcos.enterprise.portal.form.PortalQueryByPageForm;
import com.idcos.enterprise.portal.form.PortalRoleQueryByPageForm;

/**
 * manager层controller相关的接口自动生成，此文件属于自动生成的，请勿直接修改,具体可以参考codegen工程
 * Generated by <tt>controller-codegen</tt> on 2015-10-30 15:00:49.
 *
 * @author jiaohuizhe
 * @version PortalRoleQueryManager.java, v 1.1 2015-10-30 15:00:49 jiaohuizhe Exp $
 */
public interface PortalRoleQueryManager {

    /**
     * 获取某个角色信息
     *
     * @param id
     * @return BaseResultVO
     */
    CommonResult<?> queryById(String id);

    /**
     * 获取某个角色信息
     *
     * @param id
     * @return BaseResultVO
     */
    CommonResult<?> queryGroupsById(String id);

    /**
     * 获取某个角色信息
     *
     * @param id
     * @return BaseResultVO
     */
    CommonResult<?> queryPermissionsById(String id);

    /**
     * 获取某个角色信息
     *
     * @param id
     * @return BaseResultVO
     */
    CommonResult<?> queryUsersById(String id);

    /**
     * 查询用户所关联的角色信息
     *
     * @param form
     * @return
     */
    CommonResult<?> queryRolePageByUserIdAndCnd(PortalQueryByPageForm form);

    /**
     * 查询用户组所关联的角色信息
     *
     * @param form
     * @return
     */
    CommonResult<?> queryRolePageByGroupIdAndCnd(PortalQueryByPageForm form);

    /**
     * 查询角色信息
     *
     * @param offset
     * @param limit
     * @param form
     * @return BaseResultVO
     */
    CommonResult<?> queryByPage(String offset, String limit, PortalRoleQueryByPageForm form);


    /**
     * 根据tenantId查询所有的角色信息
     *
     * @param tenantId
     * @return
     */
    CommonResult<?> queryByTenantId(String tenantId);


    /**
     * 根据tenantId和用户id查询所有的角色信息
     *
     * @param tenantId
     * @param accountNo
     * @return
     */
    CommonResult<?> queryByAccountNoAndTenantId(String accountNo, String tenantId);

}