

package com.idcos.enterprise.portal.dal.entity;

// auto generated imports

import com.idcos.cloud.core.common.BaseVO;
import com.idcos.cloud.core.dal.common.ColumnMeta;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.io.Serializable;

/**
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2015-10-29 14:50:33.
 *
 * @author system-user
 * @version com.idcos.cloud.core.dal.domain.portal.java, v 1.1 2015-10-29 14:50:33 system-user Exp $
 */

@Entity
@Table(name = "PORTAL_GROUP_USER_REL")
public class PortalGroupUserRel extends BaseVO implements Serializable {

    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========
    /**
     * 数据库字段 <tt>ID</tt>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid2")
    @Column(name = "ID")
    @ColumnMeta(name = "ID", length = 64, description = "关系ID", pk = true, unique = false, nullable = false, scale = 0)
    private String id;

    /**
     * 数据库字段 <tt>USER_ID</tt>.
     */
    @Column(name = "USER_ID")
    @ColumnMeta(name = "USER_ID", length = 64, description = "用户ID", pk = false, unique = false, nullable = false, scale = 0)
    private String userId;

    /**
     * 数据库字段 <tt>GROUP_ID</tt>.
     */
    @Column(name = "GROUP_ID")
    @ColumnMeta(name = "GROUP_ID", length = 64, description = "用户组ID", pk = false, unique = false, nullable = false, scale = 0)
    private String groupId;


    /**
     * 数据库字段 <tt>TENANT</tt>.
     */
    @Column(name = "TENANT")
    @ColumnMeta(name = "TENANT", length = 64, description = "租户code", pk = false, unique = false, nullable = false, scale = 0)
    private String tenant;


    //========== getters and setters ==========


    public String getTenant() {
        return tenant;
    }

    public void setTenant(String tenant) {
        this.tenant = tenant;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }


    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

}
