package com.idcos.enterprise.portal.dal.entity;

// auto generated imports

import com.idcos.cloud.core.common.BaseVO;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2017-09-26 09:22:12.
 *
 * @author GuanBin
 * @version com.idcos.cloud.core.dal.domain.portal.java, v 1.1 2015-09-15 09:22:12 yanlv Exp $
 */

@Entity
@Table(name = "PORTAL_DEPT")
@EntityListeners(AuditingEntityListener.class)
public class PortalDept extends BaseVO implements Serializable {

    private static final long serialVersionUID = 741231858441822688L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "custom-uuid")
    @GenericGenerator(name = "custom-uuid", strategy = "com.idcos.enterprise.portal.dal.jpa.Uuid2Generator")
    @Column(name = "ID")
    private String id;

    @Column(name = "CODE")
    private String code;

    @Column(name = "DISPLAY_NAME")
    private String displayName;

    @Column(name = "PARENT_ID")
    private String parentId;

    @Column(name = "STATUS")
    private String status;

    @Column(name = "MANAGER_ID")
    private String managerId;


    @Column(name = "REMARK")
    private String remark;

    @Column(name = "TENANT_ID")
    private String tenantId;

    @Column(name = "SOURCE_TYPE")
    private String sourceType = "native";

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "GMT_CREATE")
    @org.springframework.data.annotation.CreatedDate
    private Date gmtCreate;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "GMT_MODIFIED")
    @org.springframework.data.annotation.LastModifiedDate
    private Date gmtModified;

    //========== getters and setters ==========


    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getManagerId() {
        return managerId;
    }

    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public String getTenantId() {
        return tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}
