

package com.idcos.enterprise.portal.dal.entity;

// auto generated imports

import com.idcos.cloud.core.common.BaseVO;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2015-09-15 09:22:12.
 *
 * @author yanlv
 * @version com.idcos.cloud.core.dal.domain.portal.java, v 1.1 2015-09-15 09:22:12 yanlv Exp $
 */

@Entity
@Table(name = "PORTAL_USER")
@EntityListeners(AuditingEntityListener.class)
public class PortalUser extends BaseVO implements Serializable {

    private static final long serialVersionUID = 741231858441822688L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "custom-uuid")
    @GenericGenerator(name = "custom-uuid", strategy = "com.idcos.enterprise.portal.dal.jpa.Uuid2Generator")
    @Column(name = "ID")
    private String id;

    @Column(name = "LOGIN_ID")
    private String loginId;

    @Column(name = "NAME")
    private String name;

    @Column(name = "DEPT_ID")
    private String deptId;

    @Column(name = "TITLE")
    private String title;

    @Column(name = "MOBILE1")
    private String mobile1;

    @Column(name = "MOBILE2")
    private String mobile2;

    @Column(name = "OFFICE_TEL1")
    private String officeTel1;

    @Column(name = "RTX")
    private String rtx;

    @Column(name = "OFFICE_TEL2")
    private String officeTel2;

    @Column(name = "EMPLOYEE_TYPE")
    private String employeeType;

    @Column(name = "WEIXIN")
    private String weixin;

    @Column(name = "EMAIL")
    private String email;

    @Column(name = "IS_ACTIVE")
    private String isActive;

    @Column(name = "STATUS")
    private String status;

    @Column(name = "REMARK")
    private String remark;

    @Column(name = "TENANT_ID")
    private String tenantId;

    @Column(name = "SOURCE_TYPE")
    private String sourceType = "native";

    @Column(name = "CREATE_USER")
    private String createUser;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME")
    @org.springframework.data.annotation.CreatedDate
    private Date createTime;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LAST_MODIFIED_TIME")
    @org.springframework.data.annotation.LastModifiedDate
    private Date lastModifiedTime;

    @Column(name = "LAST_LOGIN_TIME")
    private Date lastLoginTime;

    @Column(name = "PASSWORD")
    private String password;

    @Column(name = "SALT")
    private String salt;

    //========== getters and setters ==========

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getLoginId() {
        return loginId;
    }

    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDeptId() {
        return deptId;
    }

    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getMobile1() {
        return mobile1;
    }

    public void setMobile1(String mobile1) {
        this.mobile1 = mobile1;
    }

    public String getMobile2() {
        return mobile2;
    }

    public void setMobile2(String mobile2) {
        this.mobile2 = mobile2;
    }

    public String getRtx() {
        return rtx;
    }

    public void setRtx(String rtx) {
        this.rtx = rtx;
    }

    public String getOfficeTel1() {
        return officeTel1;
    }

    public void setOfficeTel1(String officeTel1) {
        this.officeTel1 = officeTel1;
    }

    public String getOfficeTel2() {
        return officeTel2;
    }

    public void setOfficeTel2(String officeTel2) {
        this.officeTel2 = officeTel2;
    }

    public String getEmployeeType() {
        return employeeType;
    }

    public void setEmployeeType(String employeeType) {
        this.employeeType = employeeType;
    }

    public String getWeixin() {
        return weixin;
    }

    public void setWeixin(String weixin) {
        this.weixin = weixin;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getIsActive() {
        return isActive;
    }

    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getTenantId() {
        return tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }
}
