

package com.idcos.enterprise.portal.dal.entity;

// auto generated imports

import com.idcos.cloud.core.common.BaseVO;
import com.idcos.cloud.core.dal.common.ColumnMeta;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.io.Serializable;

/**
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2015-11-10 15:13:07.
 *
 * @author system-user
 * @version com.idcos.cloud.core.dal.domain.portal.java, v 1.1 2015-11-10 15:13:07 system-user Exp $
 */

@Entity
@Table(name = "PORTAL_RESOURCE")
public class PortalResource extends BaseVO implements Serializable {

    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========
    /**
     * 数据库字段 <tt>ID</tt>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid2")
    @Column(name = "ID")
    @ColumnMeta(name = "ID", length = 64, description = "主键ID", pk = true, unique = false, nullable = false, scale = 0)
    private String id;

    /**
     * 数据库字段 <tt>CODE</tt>.
     */
    @Column(name = "CODE")
    @ColumnMeta(name = "CODE", length = 64, description = "权限编码", pk = false, unique = false, nullable = false, scale = 0)
    private String code;

    /**
     * 数据库字段 <tt>NAME</tt>.
     */
    @Column(name = "NAME")
    @ColumnMeta(name = "NAME", length = 128, description = "权限名称", pk = false, unique = false, nullable = false, scale = 0)
    private String name;

    /**
     * 数据库字段 <tt>URL</tt>.
     */
    @Column(name = "URL")
    @ColumnMeta(name = "URL", length = 128, description = "权限数据url", pk = false, unique = false, nullable = false, scale = 0)
    private String url;

    /**
     * 数据库字段 <tt>APP_ID</tt>.
     */
    @Column(name = "APP_ID")
    @ColumnMeta(name = "APP_ID", length = 64, description = "系统名称", pk = false, unique = false, nullable = false, scale = 0)
    private String appId;

    /**
     * 数据库字段 <tt>REMARK</tt>.
     */
    @Column(name = "REMARK")
    @ColumnMeta(name = "REMARK", length = 256, description = "备注", pk = false, unique = false, nullable = true, scale = 0)
    private String remark;

    /**
     * 数据库字段 <tt>IS_ACTIVE</tt>.
     */
    @Column(name = "IS_ACTIVE")
    @ColumnMeta(name = "IS_ACTIVE", length = 1, description = "是否有效", pk = false, unique = false, nullable = true, scale = 0)
    private String isActive;


    /**
     * 数据库字段 <tt>TENANT</tt>.
     */
    @Column(name = "TENANT")
    @ColumnMeta(name = "TENANT", length = 64, description = "租户code", pk = false, unique = false, nullable = false, scale = 0)
    private String tenant;
    //========== getters and setters ==========


    public String getTenant() {
        return tenant;
    }

    public void setTenant(String tenant) {
        this.tenant = tenant;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getIsActive() {
        return isActive;
    }

    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String systemName) {
        this.appId = systemName;
    }

}
