

package com.idcos.enterprise.portal.dal.entity;

// auto generated imports

import com.idcos.cloud.core.common.BaseVO;
import com.idcos.cloud.core.dal.common.ColumnMeta;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2015-09-15 09:22:12.
 *
 * @author yanlv
 * @version com.idcos.cloud.core.dal.domain.portal.java, v 1.1 2015-09-15 09:22:12 yanlv Exp $
 */

@Entity
@Table(name = "PORTAL_USER_GROUP")
@EntityListeners(AuditingEntityListener.class)
public class PortalUserGroup extends BaseVO implements Serializable {

    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========
    /**
     * This property corresponds to db column <tt>ID</tt>.
     * 字段备注:<tt>用户组ID</tt>
     * 字段类型:<tt>varchar</tt>
     * 字段长度:<tt>64</tt>
     * 可否为空:<tt>不可为空</tt>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid2")
    @Column(name = "ID")
    private String id;

    /**
     * This property corresponds to db column <tt>NAME</tt>.
     * 字段备注:<tt>用户组名称</tt>
     * 字段类型:<tt>varchar</tt>
     * 字段长度:<tt>128</tt>
     * 可否为空:<tt>不可为空</tt>
     */
    @Column(name = "NAME")
    private String name;

    /**
     * This property corresponds to db column <tt>NAME</tt>.
     * 字段备注:<tt>用户组名称</tt>
     * 字段类型:<tt>varchar</tt>
     * 字段长度:<tt>128</tt>
     * 可否为空:<tt>不可为空</tt>
     */
    @Column(name = "TYPE")
    private String type;

    /**
     * This property corresponds to db column <tt>REMARK</tt>.
     * 字段备注:<tt>备注</tt>
     * 字段类型:<tt>varchar</tt>
     * 字段长度:<tt>256</tt>
     * 可否为空:<tt>不可为空</tt>
     */
    @Column(name = "REMARK")
    private String remark;

    /**
     * This property corresponds to db column <tt>CREATE_USER</tt>.
     * 字段备注:<tt>创建人</tt>
     * 字段类型:<tt>varchar</tt>
     * 字段长度:<tt>64</tt>
     * 可否为空:<tt>不可为空</tt>
     */
    @Column(name = "CREATE_USER")
    private String createUser;

    /**
     * This property corresponds to db column <tt>GMT_CREATE</tt>.
     * 字段备注:<tt>创建时间</tt>
     * 字段类型:<tt>datetime</tt>
     * 字段长度:<tt>19</tt>
     * 可否为空:<tt>不可为空</tt>
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "GMT_CREATE")
    @ColumnMeta(name = "GMT_CREATE", length = 19, description = "", pk = false, unique = false, nullable = false, scale = 0)
    @org.springframework.data.annotation.CreatedDate
    private Date gmtCreate;

    /**
     * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
     * 字段备注:<tt>最后修改时间</tt>
     * 字段类型:<tt>datetime</tt>
     * 字段长度:<tt>19</tt>
     * 可否为空:<tt>不可为空</tt>
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "GMT_MODIFIED")
    @ColumnMeta(name = "GMT_MODIFIED", length = 19, description = "", pk = false, unique = false, nullable = true, scale = 0)
    @org.springframework.data.annotation.LastModifiedDate
    private Date gmtModified;

    /**
     * This property corresponds to db column <tt>IS_ACTIVE</tt>.
     * 字段备注:<tt>是否有效</tt>
     * 字段类型:<tt>char</tt>
     * 字段长度:<tt>1</tt>
     * 可否为空:<tt>不可为空</tt>
     */
    @Column(name = "IS_ACTIVE")
    private String isActive;

    @Column(name = "TENANT")
    private String tenant;

    //========== getters and setters ==========

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTenant() {
        return tenant;
    }

    public void setTenant(String tenant) {
        this.tenant = tenant;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getIsActive() {
        return isActive;
    }

    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

}
