

package com.idcos.enterprise.portal.dal.entity;

// auto generated imports

import com.idcos.cloud.core.common.BaseVO;
import com.idcos.cloud.core.dal.common.ColumnMeta;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2017-09-26 09:22:12.
 *
 * @author GuanBin
 * @version com.idcos.cloud.core.dal.domain.portal.java, v 1.1 2015-09-15 09:22:12 yanlv Exp $
 */

@Entity
@Table(name = "PORTAL_TENANT")
@EntityListeners(AuditingEntityListener.class)
public class PortalTenant extends BaseVO implements Serializable {

    private static final long serialVersionUID = 741231858441822688L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid2")
    @Column(name = "ID")
    private String id;

    @Column(name = "NAME")
    private String name;

    @Column(name = "DISPLAY_NAME")
    private String displayName;


    /**
     * This property corresponds to db column <tt>GMT_CREATE</tt>.
     * 字段备注:<tt>创建时间</tt>
     * 字段类型:<tt>datetime</tt>
     * 字段长度:<tt>19</tt>
     * 可否为空:<tt>不可为空</tt>
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "GMT_CREATE")
    @ColumnMeta(name = "GMT_CREATE", length = 19, description = "", pk = false, unique = false, nullable = false, scale = 0)
    @org.springframework.data.annotation.CreatedDate
    private Date gmtCreate;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "GMT_MODIFIED")
    @org.springframework.data.annotation.LastModifiedDate
    private Date gmtModified;

    @Column(name = "IS_ACTIVE")
    private String isActive;

    //========== getters and setters ==========


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getIsActive() {
        return isActive;
    }

    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
}
