

package com.idcos.enterprise.portal.dal.entity;

// auto generated imports

import com.idcos.cloud.core.common.BaseVO;
import com.idcos.cloud.core.dal.common.ColumnMeta;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.io.Serializable;

/**
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2015-11-07 10:08:49.
 *
 * @author system-user
 * @version com.idcos.cloud.core.dal.domain.portal.java, v 1.1 2015-11-07 10:08:49 system-user Exp $
 */

@Entity
@Table(name = "PORTAL_PERMISSION")
public class PortalPermission extends BaseVO implements Serializable {

    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========
    /**
     * 数据库字段 <tt>ID</tt>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid2")
    @Column(name = "ID")
    @ColumnMeta(name = "ID", length = 64, description = "授权信息ID", pk = true, unique = false, nullable = false, scale = 0)
    private String id;

    /**
     * 数据库字段 <tt>APP_ID</tt>.
     */
    @Column(name = "APP_ID")
    @ColumnMeta(name = "APP_ID", length = 64, description = "应用系统名称", pk = false, unique = false, nullable = true, scale = 0)
    private String appId;

    /**
     * 数据库字段 <tt>AUTH_RES_TYPE</tt>.
     */
    @Column(name = "AUTH_RES_TYPE")
    @ColumnMeta(name = "AUTH_RES_TYPE", length = 64, description = "权限资源类型", pk = false, unique = false, nullable = false, scale = 0)
    private String authResType;

    /**
     * 数据库字段 <tt>AUTH_RES_NAME</tt>.
     */
    @Column(name = "AUTH_RES_NAME")
    @ColumnMeta(name = "AUTH_RES_NAME", length = 64, description = "权限资源名称", pk = false, unique = false, nullable = false, scale = 0)
    private String authResName;

    /**
     * 数据库字段 <tt>AUTH_RES_ID</tt>.
     */
    @Column(name = "AUTH_RES_ID")
    @ColumnMeta(name = "AUTH_RES_ID", length = 64, description = "权限资源ID", pk = false, unique = false, nullable = false, scale = 0)
    private String authResId;

    /**
     * 数据库字段 <tt>AUTH_OBJ_TYPE</tt>.
     */
    @Column(name = "AUTH_OBJ_TYPE")
    @ColumnMeta(name = "AUTH_OBJ_TYPE", length = 64, description = "授权对象类型", pk = false, unique = false, nullable = false, scale = 0)
    private String authObjType;

    /**
     * 数据库字段 <tt>AUTH_OBJ_ID</tt>.
     */
    @Column(name = "AUTH_OBJ_ID")
    @ColumnMeta(name = "AUTH_OBJ_ID", length = 64, description = "授权对象ID", pk = false, unique = false, nullable = false, scale = 0)
    private String authObjId;

    /**
     * 数据库字段 <tt>TENANT</tt>.
     */
    @Column(name = "TENANT")
    @ColumnMeta(name = "TENANT", length = 64, description = "租户code", pk = false, unique = false, nullable = true, scale = 0)
    private String tenant;

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getTenant() {
        return tenant;
    }

    public void setTenant(String tenant) {
        this.tenant = tenant;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAuthResType() {
        return authResType;
    }

    public void setAuthResType(String authResType) {
        this.authResType = authResType;
    }

    public String getAuthResId() {
        return authResId;
    }

    public void setAuthResId(String authResId) {
        this.authResId = authResId;
    }

    public String getAuthObjType() {
        return authObjType;
    }

    public void setAuthObjType(String authObjType) {
        this.authObjType = authObjType;
    }

    public String getAuthObjId() {
        return authObjId;
    }

    public void setAuthObjId(String authObjId) {
        this.authObjId = authObjId;
    }

    public String getAuthResName() {
        return authResName;
    }

    public void setAuthResName(String authResName) {
        this.authResName = authResName;
    }

}
