/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables;


import com.idcos.enterprise.jooq.Clouduam;
import com.idcos.enterprise.jooq.Keys;
import com.idcos.enterprise.jooq.tables.records.PortalGroupRoleRelRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 用户组与角色关系表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalGroupRoleRel extends TableImpl<PortalGroupRoleRelRecord> {

	private static final long serialVersionUID = -940972561;

	/**
	 * The reference instance of <code>clouduam.PORTAL_GROUP_ROLE_REL</code>
	 */
	public static final PortalGroupRoleRel PORTAL_GROUP_ROLE_REL = new PortalGroupRoleRel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PortalGroupRoleRelRecord> getRecordType() {
		return PortalGroupRoleRelRecord.class;
	}

	/**
	 * The column <code>clouduam.PORTAL_GROUP_ROLE_REL.ID</code>. 关系ID
	 */
	public final TableField<PortalGroupRoleRelRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "关系ID");

	/**
	 * The column <code>clouduam.PORTAL_GROUP_ROLE_REL.ROLE_ID</code>. 角色ID
	 */
	public final TableField<PortalGroupRoleRelRecord, String> ROLE_ID = createField("ROLE_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "角色ID");

	/**
	 * The column <code>clouduam.PORTAL_GROUP_ROLE_REL.GROUP_ID</code>. 用户组ID
	 */
	public final TableField<PortalGroupRoleRelRecord, String> GROUP_ID = createField("GROUP_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "用户组ID");

	/**
	 * The column <code>clouduam.PORTAL_GROUP_ROLE_REL.TENANT</code>. 租户code
	 */
	public final TableField<PortalGroupRoleRelRecord, String> TENANT = createField("TENANT", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "租户code");

	/**
	 * Create a <code>clouduam.PORTAL_GROUP_ROLE_REL</code> table reference
	 */
	public PortalGroupRoleRel() {
		this("PORTAL_GROUP_ROLE_REL", null);
	}

	/**
	 * Create an aliased <code>clouduam.PORTAL_GROUP_ROLE_REL</code> table reference
	 */
	public PortalGroupRoleRel(String alias) {
		this(alias, PORTAL_GROUP_ROLE_REL);
	}

	private PortalGroupRoleRel(String alias, Table<PortalGroupRoleRelRecord> aliased) {
		this(alias, aliased, null);
	}

	private PortalGroupRoleRel(String alias, Table<PortalGroupRoleRelRecord> aliased, Field<?>[] parameters) {
		super(alias, Clouduam.CLOUDUAM, aliased, parameters, "用户组与角色关系表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PortalGroupRoleRelRecord> getPrimaryKey() {
		return Keys.KEY_PORTAL_GROUP_ROLE_REL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PortalGroupRoleRelRecord>> getKeys() {
		return Arrays.<UniqueKey<PortalGroupRoleRelRecord>>asList(Keys.KEY_PORTAL_GROUP_ROLE_REL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalGroupRoleRel as(String alias) {
		return new PortalGroupRoleRel(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PortalGroupRoleRel rename(String name) {
		return new PortalGroupRoleRel(name, null);
	}
}
