/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables;


import com.idcos.enterprise.jooq.Clouduam;
import com.idcos.enterprise.jooq.Keys;
import com.idcos.enterprise.jooq.tables.records.PortalPermissionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 授权信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalPermission extends TableImpl<PortalPermissionRecord> {

	private static final long serialVersionUID = 1006339669;

	/**
	 * The reference instance of <code>clouduam.PORTAL_PERMISSION</code>
	 */
	public static final PortalPermission PORTAL_PERMISSION = new PortalPermission();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PortalPermissionRecord> getRecordType() {
		return PortalPermissionRecord.class;
	}

	/**
	 * The column <code>clouduam.PORTAL_PERMISSION.ID</code>. 授权信息ID
	 */
	public final TableField<PortalPermissionRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "授权信息ID");

	/**
	 * The column <code>clouduam.PORTAL_PERMISSION.APP_ID</code>. 应用系统名称
	 */
	public final TableField<PortalPermissionRecord, String> APP_ID = createField("APP_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "应用系统名称");

	/**
	 * The column <code>clouduam.PORTAL_PERMISSION.AUTH_RES_TYPE</code>. 权限资源类型
	 */
	public final TableField<PortalPermissionRecord, String> AUTH_RES_TYPE = createField("AUTH_RES_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "权限资源类型");

	/**
	 * The column <code>clouduam.PORTAL_PERMISSION.AUTH_RES_ID</code>. 权限资源ID
	 */
	public final TableField<PortalPermissionRecord, String> AUTH_RES_ID = createField("AUTH_RES_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "权限资源ID");

	/**
	 * The column <code>clouduam.PORTAL_PERMISSION.AUTH_RES_NAME</code>.
	 */
	public final TableField<PortalPermissionRecord, String> AUTH_RES_NAME = createField("AUTH_RES_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>clouduam.PORTAL_PERMISSION.AUTH_OBJ_ID</code>. 授权对象ID
	 */
	public final TableField<PortalPermissionRecord, String> AUTH_OBJ_ID = createField("AUTH_OBJ_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "授权对象ID");

	/**
	 * The column <code>clouduam.PORTAL_PERMISSION.AUTH_OBJ_TYPE</code>. 授权对象类型
	 */
	public final TableField<PortalPermissionRecord, String> AUTH_OBJ_TYPE = createField("AUTH_OBJ_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "授权对象类型");

	/**
	 * The column <code>clouduam.PORTAL_PERMISSION.TENANT</code>. 租户code
	 */
	public final TableField<PortalPermissionRecord, String> TENANT = createField("TENANT", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "租户code");

	/**
	 * Create a <code>clouduam.PORTAL_PERMISSION</code> table reference
	 */
	public PortalPermission() {
		this("PORTAL_PERMISSION", null);
	}

	/**
	 * Create an aliased <code>clouduam.PORTAL_PERMISSION</code> table reference
	 */
	public PortalPermission(String alias) {
		this(alias, PORTAL_PERMISSION);
	}

	private PortalPermission(String alias, Table<PortalPermissionRecord> aliased) {
		this(alias, aliased, null);
	}

	private PortalPermission(String alias, Table<PortalPermissionRecord> aliased, Field<?>[] parameters) {
		super(alias, Clouduam.CLOUDUAM, aliased, parameters, "授权信息表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PortalPermissionRecord> getPrimaryKey() {
		return Keys.KEY_PORTAL_PERMISSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PortalPermissionRecord>> getKeys() {
		return Arrays.<UniqueKey<PortalPermissionRecord>>asList(Keys.KEY_PORTAL_PERMISSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalPermission as(String alias) {
		return new PortalPermission(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PortalPermission rename(String name) {
		return new PortalPermission(name, null);
	}
}
