/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables;


import com.idcos.enterprise.jooq.Clouduam;
import com.idcos.enterprise.jooq.Keys;
import com.idcos.enterprise.jooq.tables.records.PortalDeptRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 部门信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalDept extends TableImpl<PortalDeptRecord> {

	private static final long serialVersionUID = -1864948499;

	/**
	 * The reference instance of <code>clouduam.PORTAL_DEPT</code>
	 */
	public static final PortalDept PORTAL_DEPT = new PortalDept();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PortalDeptRecord> getRecordType() {
		return PortalDeptRecord.class;
	}

	/**
	 * The column <code>clouduam.PORTAL_DEPT.ID</code>.
	 */
	public final TableField<PortalDeptRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>clouduam.PORTAL_DEPT.CODE</code>. 部门code
	 */
	public final TableField<PortalDeptRecord, String> CODE = createField("CODE", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "部门code");

	/**
	 * The column <code>clouduam.PORTAL_DEPT.DISPLAY_NAME</code>. 部门名称
	 */
	public final TableField<PortalDeptRecord, String> DISPLAY_NAME = createField("DISPLAY_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "部门名称");

	/**
	 * The column <code>clouduam.PORTAL_DEPT.PARENT_ID</code>. 父项目id
	 */
	public final TableField<PortalDeptRecord, String> PARENT_ID = createField("PARENT_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "父项目id");

	/**
	 * The column <code>clouduam.PORTAL_DEPT.STATUS</code>. 部门状态
	 */
	public final TableField<PortalDeptRecord, String> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "部门状态");

	/**
	 * The column <code>clouduam.PORTAL_DEPT.MANAGER_ID</code>.
	 */
	public final TableField<PortalDeptRecord, String> MANAGER_ID = createField("MANAGER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>clouduam.PORTAL_DEPT.REMARK</code>. 备注
	 */
	public final TableField<PortalDeptRecord, String> REMARK = createField("REMARK", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "备注");

	/**
	 * The column <code>clouduam.PORTAL_DEPT.TENANT_ID</code>. 租户id
	 */
	public final TableField<PortalDeptRecord, String> TENANT_ID = createField("TENANT_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "租户id");

	/**
	 * The column <code>clouduam.PORTAL_DEPT.SOURCE_TYPE</code>. 数据同步来源来源，默认值native表示本系统，如果来自第三方，则需重新定义该值
	 */
	public final TableField<PortalDeptRecord, String> SOURCE_TYPE = createField("SOURCE_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "数据同步来源来源，默认值native表示本系统，如果来自第三方，则需重新定义该值");

	/**
	 * The column <code>clouduam.PORTAL_DEPT.GMT_CREATE</code>. 创建日期
	 */
	public final TableField<PortalDeptRecord, Timestamp> GMT_CREATE = createField("GMT_CREATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建日期");

	/**
	 * The column <code>clouduam.PORTAL_DEPT.GMT_MODIFIED</code>. 修改日期
	 */
	public final TableField<PortalDeptRecord, Timestamp> GMT_MODIFIED = createField("GMT_MODIFIED", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改日期");

	/**
	 * Create a <code>clouduam.PORTAL_DEPT</code> table reference
	 */
	public PortalDept() {
		this("PORTAL_DEPT", null);
	}

	/**
	 * Create an aliased <code>clouduam.PORTAL_DEPT</code> table reference
	 */
	public PortalDept(String alias) {
		this(alias, PORTAL_DEPT);
	}

	private PortalDept(String alias, Table<PortalDeptRecord> aliased) {
		this(alias, aliased, null);
	}

	private PortalDept(String alias, Table<PortalDeptRecord> aliased, Field<?>[] parameters) {
		super(alias, Clouduam.CLOUDUAM, aliased, parameters, "部门信息表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PortalDeptRecord> getPrimaryKey() {
		return Keys.KEY_PORTAL_DEPT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PortalDeptRecord>> getKeys() {
		return Arrays.<UniqueKey<PortalDeptRecord>>asList(Keys.KEY_PORTAL_DEPT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDept as(String alias) {
		return new PortalDept(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PortalDept rename(String name) {
		return new PortalDept(name, null);
	}
}
