/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables;


import com.idcos.enterprise.jooq.Clouduam;
import com.idcos.enterprise.jooq.tables.records.PortalGroupUserRelRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * 用户组用户关系表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalGroupUserRel extends TableImpl<PortalGroupUserRelRecord> {

	private static final long serialVersionUID = 2025527354;

	/**
	 * The reference instance of <code>clouduam.PORTAL_GROUP_USER_REL</code>
	 */
	public static final PortalGroupUserRel PORTAL_GROUP_USER_REL = new PortalGroupUserRel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PortalGroupUserRelRecord> getRecordType() {
		return PortalGroupUserRelRecord.class;
	}

	/**
	 * The column <code>clouduam.PORTAL_GROUP_USER_REL.ID</code>. 关系ID
	 */
	public final TableField<PortalGroupUserRelRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "关系ID");

	/**
	 * The column <code>clouduam.PORTAL_GROUP_USER_REL.USER_ID</code>. 用户ID
	 */
	public final TableField<PortalGroupUserRelRecord, String> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "用户ID");

	/**
	 * The column <code>clouduam.PORTAL_GROUP_USER_REL.GROUP_ID</code>. 用户组ID
	 */
	public final TableField<PortalGroupUserRelRecord, String> GROUP_ID = createField("GROUP_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "用户组ID");

	/**
	 * The column <code>clouduam.PORTAL_GROUP_USER_REL.TENANT</code>. 租户code
	 */
	public final TableField<PortalGroupUserRelRecord, String> TENANT = createField("TENANT", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "租户code");

	/**
	 * Create a <code>clouduam.PORTAL_GROUP_USER_REL</code> table reference
	 */
	public PortalGroupUserRel() {
		this("PORTAL_GROUP_USER_REL", null);
	}

	/**
	 * Create an aliased <code>clouduam.PORTAL_GROUP_USER_REL</code> table reference
	 */
	public PortalGroupUserRel(String alias) {
		this(alias, PORTAL_GROUP_USER_REL);
	}

	private PortalGroupUserRel(String alias, Table<PortalGroupUserRelRecord> aliased) {
		this(alias, aliased, null);
	}

	private PortalGroupUserRel(String alias, Table<PortalGroupUserRelRecord> aliased, Field<?>[] parameters) {
		super(alias, Clouduam.CLOUDUAM, aliased, parameters, "用户组用户关系表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalGroupUserRel as(String alias) {
		return new PortalGroupUserRel(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PortalGroupUserRel rename(String name) {
		return new PortalGroupUserRel(name, null);
	}
}
