/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables;


import com.idcos.enterprise.jooq.Clouduam;
import com.idcos.enterprise.jooq.Keys;
import com.idcos.enterprise.jooq.tables.records.PortalDeptRoleRelRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 部门与角色的关系表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalDeptRoleRel extends TableImpl<PortalDeptRoleRelRecord> {

	private static final long serialVersionUID = 92442799;

	/**
	 * The reference instance of <code>clouduam.PORTAL_DEPT_ROLE_REL</code>
	 */
	public static final PortalDeptRoleRel PORTAL_DEPT_ROLE_REL = new PortalDeptRoleRel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PortalDeptRoleRelRecord> getRecordType() {
		return PortalDeptRoleRelRecord.class;
	}

	/**
	 * The column <code>clouduam.PORTAL_DEPT_ROLE_REL.ID</code>. id
	 */
	public final TableField<PortalDeptRoleRelRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "id");

	/**
	 * The column <code>clouduam.PORTAL_DEPT_ROLE_REL.DEPT_ID</code>. 部门id
	 */
	public final TableField<PortalDeptRoleRelRecord, String> DEPT_ID = createField("DEPT_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "部门id");

	/**
	 * The column <code>clouduam.PORTAL_DEPT_ROLE_REL.ROLE_ID</code>. 角色id
	 */
	public final TableField<PortalDeptRoleRelRecord, String> ROLE_ID = createField("ROLE_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "角色id");

	/**
	 * Create a <code>clouduam.PORTAL_DEPT_ROLE_REL</code> table reference
	 */
	public PortalDeptRoleRel() {
		this("PORTAL_DEPT_ROLE_REL", null);
	}

	/**
	 * Create an aliased <code>clouduam.PORTAL_DEPT_ROLE_REL</code> table reference
	 */
	public PortalDeptRoleRel(String alias) {
		this(alias, PORTAL_DEPT_ROLE_REL);
	}

	private PortalDeptRoleRel(String alias, Table<PortalDeptRoleRelRecord> aliased) {
		this(alias, aliased, null);
	}

	private PortalDeptRoleRel(String alias, Table<PortalDeptRoleRelRecord> aliased, Field<?>[] parameters) {
		super(alias, Clouduam.CLOUDUAM, aliased, parameters, "部门与角色的关系表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PortalDeptRoleRelRecord> getPrimaryKey() {
		return Keys.KEY_PORTAL_DEPT_ROLE_REL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PortalDeptRoleRelRecord>> getKeys() {
		return Arrays.<UniqueKey<PortalDeptRoleRelRecord>>asList(Keys.KEY_PORTAL_DEPT_ROLE_REL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRoleRel as(String alias) {
		return new PortalDeptRoleRel(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PortalDeptRoleRel rename(String name) {
		return new PortalDeptRoleRel(name, null);
	}
}
