/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables;


import com.idcos.enterprise.jooq.Clouduam;
import com.idcos.enterprise.jooq.Keys;
import com.idcos.enterprise.jooq.tables.records.PortalUserRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 用户信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalUser extends TableImpl<PortalUserRecord> {

	private static final long serialVersionUID = -1616998714;

	/**
	 * The reference instance of <code>clouduam.PORTAL_USER</code>
	 */
	public static final PortalUser PORTAL_USER = new PortalUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PortalUserRecord> getRecordType() {
		return PortalUserRecord.class;
	}

	/**
	 * The column <code>clouduam.PORTAL_USER.ID</code>. 用户ID
	 */
	public final TableField<PortalUserRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "用户ID");

	/**
	 * The column <code>clouduam.PORTAL_USER.NAME</code>.
	 */
	public final TableField<PortalUserRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>clouduam.PORTAL_USER.LOGIN_ID</code>. 登录名
	 */
	public final TableField<PortalUserRecord, String> LOGIN_ID = createField("LOGIN_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "登录名");

	/**
	 * The column <code>clouduam.PORTAL_USER.DEPT_ID</code>. 部门id
	 */
	public final TableField<PortalUserRecord, String> DEPT_ID = createField("DEPT_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "部门id");

	/**
	 * The column <code>clouduam.PORTAL_USER.TITLE</code>. 标签
	 */
	public final TableField<PortalUserRecord, String> TITLE = createField("TITLE", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "标签");

	/**
	 * The column <code>clouduam.PORTAL_USER.MOBILE1</code>.
	 */
	public final TableField<PortalUserRecord, String> MOBILE1 = createField("MOBILE1", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>clouduam.PORTAL_USER.WEIXIN</code>. 标签
	 */
	public final TableField<PortalUserRecord, String> WEIXIN = createField("WEIXIN", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "标签");

	/**
	 * The column <code>clouduam.PORTAL_USER.EMAIL</code>. 邮箱
	 */
	public final TableField<PortalUserRecord, String> EMAIL = createField("EMAIL", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "邮箱");

	/**
	 * The column <code>clouduam.PORTAL_USER.IS_ACTIVE</code>. 是否有效
	 */
	public final TableField<PortalUserRecord, String> IS_ACTIVE = createField("IS_ACTIVE", org.jooq.impl.SQLDataType.CHAR.length(1), this, "是否有效");

	/**
	 * The column <code>clouduam.PORTAL_USER.STATUS</code>. 用户类型：INIT、ENABLED、DISABLED、LOCKED
	 */
	public final TableField<PortalUserRecord, String> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "用户类型：INIT、ENABLED、DISABLED、LOCKED");

	/**
	 * The column <code>clouduam.PORTAL_USER.REMARK</code>. 备注
	 */
	public final TableField<PortalUserRecord, String> REMARK = createField("REMARK", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "备注");

	/**
	 * The column <code>clouduam.PORTAL_USER.TENANT_ID</code>. 租户编码
	 */
	public final TableField<PortalUserRecord, String> TENANT_ID = createField("TENANT_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "租户编码");

	/**
	 * The column <code>clouduam.PORTAL_USER.SOURCE_TYPE</code>. 数据同步来源来源，默认值native表示本系统，如果来自第三方，则需重新定义该值
	 */
	public final TableField<PortalUserRecord, String> SOURCE_TYPE = createField("SOURCE_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "数据同步来源来源，默认值native表示本系统，如果来自第三方，则需重新定义该值");

	/**
	 * The column <code>clouduam.PORTAL_USER.LAST_MODIFIED_TIME</code>. 最后登录时间
	 */
	public final TableField<PortalUserRecord, Timestamp> LAST_MODIFIED_TIME = createField("LAST_MODIFIED_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后登录时间");

	/**
	 * The column <code>clouduam.PORTAL_USER.CREATE_TIME</code>. 创建时间
	 */
	public final TableField<PortalUserRecord, Timestamp> CREATE_TIME = createField("CREATE_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

	/**
	 * The column <code>clouduam.PORTAL_USER.LAST_LOGIN_TIME</code>. 最后修改时间
	 */
	public final TableField<PortalUserRecord, Timestamp> LAST_LOGIN_TIME = createField("LAST_LOGIN_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后修改时间");

	/**
	 * The column <code>clouduam.PORTAL_USER.PASSWORD</code>. 密码
	 */
	public final TableField<PortalUserRecord, String> PASSWORD = createField("PASSWORD", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "密码");

	/**
	 * The column <code>clouduam.PORTAL_USER.SALT</code>. 密码盐
	 */
	public final TableField<PortalUserRecord, String> SALT = createField("SALT", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "密码盐");

	/**
	 * The column <code>clouduam.PORTAL_USER.MOBILE2</code>.
	 */
	public final TableField<PortalUserRecord, String> MOBILE2 = createField("MOBILE2", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>clouduam.PORTAL_USER.RTX</code>. RTX沟通工具
	 */
	public final TableField<PortalUserRecord, String> RTX = createField("RTX", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "RTX沟通工具");

	/**
	 * The column <code>clouduam.PORTAL_USER.OFFICE_TEL1</code>.
	 */
	public final TableField<PortalUserRecord, String> OFFICE_TEL1 = createField("OFFICE_TEL1", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>clouduam.PORTAL_USER.OFFICE_TEL2</code>.
	 */
	public final TableField<PortalUserRecord, String> OFFICE_TEL2 = createField("OFFICE_TEL2", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>clouduam.PORTAL_USER.EMPLOYEE_TYPE</code>.
	 */
	public final TableField<PortalUserRecord, String> EMPLOYEE_TYPE = createField("EMPLOYEE_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>clouduam.PORTAL_USER.CREATE_USER</code>. 创建人
	 */
	public final TableField<PortalUserRecord, String> CREATE_USER = createField("CREATE_USER", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "创建人");

	/**
	 * Create a <code>clouduam.PORTAL_USER</code> table reference
	 */
	public PortalUser() {
		this("PORTAL_USER", null);
	}

	/**
	 * Create an aliased <code>clouduam.PORTAL_USER</code> table reference
	 */
	public PortalUser(String alias) {
		this(alias, PORTAL_USER);
	}

	private PortalUser(String alias, Table<PortalUserRecord> aliased) {
		this(alias, aliased, null);
	}

	private PortalUser(String alias, Table<PortalUserRecord> aliased, Field<?>[] parameters) {
		super(alias, Clouduam.CLOUDUAM, aliased, parameters, "用户信息表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PortalUserRecord> getPrimaryKey() {
		return Keys.KEY_PORTAL_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PortalUserRecord>> getKeys() {
		return Arrays.<UniqueKey<PortalUserRecord>>asList(Keys.KEY_PORTAL_USER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalUser as(String alias) {
		return new PortalUser(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PortalUser rename(String name) {
		return new PortalUser(name, null);
	}
}
