/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables;


import com.idcos.enterprise.jooq.Clouduam;
import com.idcos.enterprise.jooq.Keys;
import com.idcos.enterprise.jooq.tables.records.PortalRoleRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 角色信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalRole extends TableImpl<PortalRoleRecord> {

	private static final long serialVersionUID = 1771649252;

	/**
	 * The reference instance of <code>clouduam.PORTAL_ROLE</code>
	 */
	public static final PortalRole PORTAL_ROLE = new PortalRole();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PortalRoleRecord> getRecordType() {
		return PortalRoleRecord.class;
	}

	/**
	 * The column <code>clouduam.PORTAL_ROLE.ID</code>. 角色ID
	 */
	public final TableField<PortalRoleRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "角色ID");

	/**
	 * The column <code>clouduam.PORTAL_ROLE.CODE</code>. 角色编码
	 */
	public final TableField<PortalRoleRecord, String> CODE = createField("CODE", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "角色编码");

	/**
	 * The column <code>clouduam.PORTAL_ROLE.NAME</code>. 角色名称
	 */
	public final TableField<PortalRoleRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "角色名称");

	/**
	 * The column <code>clouduam.PORTAL_ROLE.REMARK</code>. 角色描述
	 */
	public final TableField<PortalRoleRecord, String> REMARK = createField("REMARK", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "角色描述");

	/**
	 * The column <code>clouduam.PORTAL_ROLE.CREATE_USER</code>. 创建人
	 */
	public final TableField<PortalRoleRecord, String> CREATE_USER = createField("CREATE_USER", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "创建人");

	/**
	 * The column <code>clouduam.PORTAL_ROLE.GMT_CREATE</code>. 创建时间
	 */
	public final TableField<PortalRoleRecord, Timestamp> GMT_CREATE = createField("GMT_CREATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

	/**
	 * The column <code>clouduam.PORTAL_ROLE.GMT_MODIFIED</code>. 最后修改时间
	 */
	public final TableField<PortalRoleRecord, Timestamp> GMT_MODIFIED = createField("GMT_MODIFIED", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后修改时间");

	/**
	 * The column <code>clouduam.PORTAL_ROLE.IS_ACTIVE</code>. 是否有效
	 */
	public final TableField<PortalRoleRecord, String> IS_ACTIVE = createField("IS_ACTIVE", org.jooq.impl.SQLDataType.CHAR.length(1), this, "是否有效");

	/**
	 * The column <code>clouduam.PORTAL_ROLE.TENANT</code>. 租户code
	 */
	public final TableField<PortalRoleRecord, String> TENANT = createField("TENANT", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "租户code");

	/**
	 * Create a <code>clouduam.PORTAL_ROLE</code> table reference
	 */
	public PortalRole() {
		this("PORTAL_ROLE", null);
	}

	/**
	 * Create an aliased <code>clouduam.PORTAL_ROLE</code> table reference
	 */
	public PortalRole(String alias) {
		this(alias, PORTAL_ROLE);
	}

	private PortalRole(String alias, Table<PortalRoleRecord> aliased) {
		this(alias, aliased, null);
	}

	private PortalRole(String alias, Table<PortalRoleRecord> aliased, Field<?>[] parameters) {
		super(alias, Clouduam.CLOUDUAM, aliased, parameters, "角色信息表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PortalRoleRecord> getPrimaryKey() {
		return Keys.KEY_PORTAL_ROLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PortalRoleRecord>> getKeys() {
		return Arrays.<UniqueKey<PortalRoleRecord>>asList(Keys.KEY_PORTAL_ROLE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRole as(String alias) {
		return new PortalRole(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PortalRole rename(String name) {
		return new PortalRole(name, null);
	}
}
