/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables;


import com.idcos.enterprise.jooq.Clouduam;
import com.idcos.enterprise.jooq.Keys;
import com.idcos.enterprise.jooq.tables.records.PortalUserGroupRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 用户组信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalUserGroup extends TableImpl<PortalUserGroupRecord> {

	private static final long serialVersionUID = -888338359;

	/**
	 * The reference instance of <code>clouduam.PORTAL_USER_GROUP</code>
	 */
	public static final PortalUserGroup PORTAL_USER_GROUP = new PortalUserGroup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PortalUserGroupRecord> getRecordType() {
		return PortalUserGroupRecord.class;
	}

	/**
	 * The column <code>clouduam.PORTAL_USER_GROUP.ID</code>. 用户组ID
	 */
	public final TableField<PortalUserGroupRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "用户组ID");

	/**
	 * The column <code>clouduam.PORTAL_USER_GROUP.NAME</code>. 用户组名称
	 */
	public final TableField<PortalUserGroupRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "用户组名称");

	/**
	 * The column <code>clouduam.PORTAL_USER_GROUP.TYPE</code>. 用户组类型
	 */
	public final TableField<PortalUserGroupRecord, String> TYPE = createField("TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "用户组类型");

	/**
	 * The column <code>clouduam.PORTAL_USER_GROUP.REMARK</code>. 备注
	 */
	public final TableField<PortalUserGroupRecord, String> REMARK = createField("REMARK", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "备注");

	/**
	 * The column <code>clouduam.PORTAL_USER_GROUP.CREATE_USER</code>. 创建人
	 */
	public final TableField<PortalUserGroupRecord, String> CREATE_USER = createField("CREATE_USER", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "创建人");

	/**
	 * The column <code>clouduam.PORTAL_USER_GROUP.GMT_CREATE</code>. 创建时间
	 */
	public final TableField<PortalUserGroupRecord, Timestamp> GMT_CREATE = createField("GMT_CREATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

	/**
	 * The column <code>clouduam.PORTAL_USER_GROUP.GMT_MODIFIED</code>. 最后修改时间
	 */
	public final TableField<PortalUserGroupRecord, Timestamp> GMT_MODIFIED = createField("GMT_MODIFIED", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "最后修改时间");

	/**
	 * The column <code>clouduam.PORTAL_USER_GROUP.IS_ACTIVE</code>. 是否有效
	 */
	public final TableField<PortalUserGroupRecord, String> IS_ACTIVE = createField("IS_ACTIVE", org.jooq.impl.SQLDataType.CHAR.length(1), this, "是否有效");

	/**
	 * The column <code>clouduam.PORTAL_USER_GROUP.TENANT</code>. 租户code
	 */
	public final TableField<PortalUserGroupRecord, String> TENANT = createField("TENANT", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "租户code");

	/**
	 * Create a <code>clouduam.PORTAL_USER_GROUP</code> table reference
	 */
	public PortalUserGroup() {
		this("PORTAL_USER_GROUP", null);
	}

	/**
	 * Create an aliased <code>clouduam.PORTAL_USER_GROUP</code> table reference
	 */
	public PortalUserGroup(String alias) {
		this(alias, PORTAL_USER_GROUP);
	}

	private PortalUserGroup(String alias, Table<PortalUserGroupRecord> aliased) {
		this(alias, aliased, null);
	}

	private PortalUserGroup(String alias, Table<PortalUserGroupRecord> aliased, Field<?>[] parameters) {
		super(alias, Clouduam.CLOUDUAM, aliased, parameters, "用户组信息表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PortalUserGroupRecord> getPrimaryKey() {
		return Keys.KEY_PORTAL_USER_GROUP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PortalUserGroupRecord>> getKeys() {
		return Arrays.<UniqueKey<PortalUserGroupRecord>>asList(Keys.KEY_PORTAL_USER_GROUP_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalUserGroup as(String alias) {
		return new PortalUserGroup(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PortalUserGroup rename(String name) {
		return new PortalUserGroup(name, null);
	}
}
