/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables;


import com.idcos.enterprise.jooq.Clouduam;
import com.idcos.enterprise.jooq.Keys;
import com.idcos.enterprise.jooq.tables.records.PortalTokenRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * token信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalToken extends TableImpl<PortalTokenRecord> {

	private static final long serialVersionUID = -1174958722;

	/**
	 * The reference instance of <code>clouduam.PORTAL_TOKEN</code>
	 */
	public static final PortalToken PORTAL_TOKEN = new PortalToken();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PortalTokenRecord> getRecordType() {
		return PortalTokenRecord.class;
	}

	/**
	 * The column <code>clouduam.PORTAL_TOKEN.ID</code>.
	 */
	public final TableField<PortalTokenRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>clouduam.PORTAL_TOKEN.NAME</code>. token值
	 */
	public final TableField<PortalTokenRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "token值");

	/**
	 * The column <code>clouduam.PORTAL_TOKEN.TOKEN_CRC</code>. token串的crc哈希值
	 */
	public final TableField<PortalTokenRecord, UInteger> TOKEN_CRC = createField("TOKEN_CRC", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaulted(true), this, "token串的crc哈希值");

	/**
	 * The column <code>clouduam.PORTAL_TOKEN.LOGIN_ID</code>. 登录名
	 */
	public final TableField<PortalTokenRecord, String> LOGIN_ID = createField("LOGIN_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "登录名");

	/**
	 * The column <code>clouduam.PORTAL_TOKEN.TENANT_ID</code>. 租户code
	 */
	public final TableField<PortalTokenRecord, String> TENANT_ID = createField("TENANT_ID", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "租户code");

	/**
	 * The column <code>clouduam.PORTAL_TOKEN.IS_ACTIVE</code>. 是否可用
	 */
	public final TableField<PortalTokenRecord, String> IS_ACTIVE = createField("IS_ACTIVE", org.jooq.impl.SQLDataType.CHAR.length(1), this, "是否可用");

	/**
	 * The column <code>clouduam.PORTAL_TOKEN.EXPIRE_TIME</code>. token过期时间
	 */
	public final TableField<PortalTokenRecord, Timestamp> EXPIRE_TIME = createField("EXPIRE_TIME", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "token过期时间");

	/**
	 * The column <code>clouduam.PORTAL_TOKEN.GMT_CREATE</code>. 创建日期
	 */
	public final TableField<PortalTokenRecord, Timestamp> GMT_CREATE = createField("GMT_CREATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建日期");

	/**
	 * The column <code>clouduam.PORTAL_TOKEN.GMT_MODIFIED</code>. 修改日期
	 */
	public final TableField<PortalTokenRecord, Timestamp> GMT_MODIFIED = createField("GMT_MODIFIED", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "修改日期");

	/**
	 * The column <code>clouduam.PORTAL_TOKEN.REMARK</code>. 备注
	 */
	public final TableField<PortalTokenRecord, String> REMARK = createField("REMARK", org.jooq.impl.SQLDataType.CLOB, this, "备注");

	/**
	 * Create a <code>clouduam.PORTAL_TOKEN</code> table reference
	 */
	public PortalToken() {
		this("PORTAL_TOKEN", null);
	}

	/**
	 * Create an aliased <code>clouduam.PORTAL_TOKEN</code> table reference
	 */
	public PortalToken(String alias) {
		this(alias, PORTAL_TOKEN);
	}

	private PortalToken(String alias, Table<PortalTokenRecord> aliased) {
		this(alias, aliased, null);
	}

	private PortalToken(String alias, Table<PortalTokenRecord> aliased, Field<?>[] parameters) {
		super(alias, Clouduam.CLOUDUAM, aliased, parameters, "token信息表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PortalTokenRecord> getPrimaryKey() {
		return Keys.KEY_PORTAL_TOKEN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PortalTokenRecord>> getKeys() {
		return Arrays.<UniqueKey<PortalTokenRecord>>asList(Keys.KEY_PORTAL_TOKEN_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalToken as(String alias) {
		return new PortalToken(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PortalToken rename(String name) {
		return new PortalToken(name, null);
	}
}
