/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq;


import com.idcos.enterprise.jooq.tables.PortalDept;
import com.idcos.enterprise.jooq.tables.PortalDeptRoleRel;
import com.idcos.enterprise.jooq.tables.PortalGroupRoleRel;
import com.idcos.enterprise.jooq.tables.PortalGroupUserRel;
import com.idcos.enterprise.jooq.tables.PortalPermission;
import com.idcos.enterprise.jooq.tables.PortalResource;
import com.idcos.enterprise.jooq.tables.PortalRole;
import com.idcos.enterprise.jooq.tables.PortalSysDict;
import com.idcos.enterprise.jooq.tables.PortalTenant;
import com.idcos.enterprise.jooq.tables.PortalToken;
import com.idcos.enterprise.jooq.tables.PortalUser;
import com.idcos.enterprise.jooq.tables.PortalUserGroup;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Clouduam extends SchemaImpl {

	private static final long serialVersionUID = -1532745740;

	/**
	 * The reference instance of <code>clouduam</code>
	 */
	public static final Clouduam CLOUDUAM = new Clouduam();

	/**
	 * No further instances allowed
	 */
	private Clouduam() {
		super("clouduam");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			PortalDept.PORTAL_DEPT,
			PortalDeptRoleRel.PORTAL_DEPT_ROLE_REL,
			PortalGroupRoleRel.PORTAL_GROUP_ROLE_REL,
			PortalGroupUserRel.PORTAL_GROUP_USER_REL,
			PortalPermission.PORTAL_PERMISSION,
			PortalResource.PORTAL_RESOURCE,
			PortalRole.PORTAL_ROLE,
			PortalSysDict.PORTAL_SYS_DICT,
			PortalTenant.PORTAL_TENANT,
			PortalToken.PORTAL_TOKEN,
			PortalUser.PORTAL_USER,
			PortalUserGroup.PORTAL_USER_GROUP);
	}
}
