/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq;


import com.idcos.enterprise.jooq.tables.PortalDept;
import com.idcos.enterprise.jooq.tables.PortalDeptRoleRel;
import com.idcos.enterprise.jooq.tables.PortalGroupRoleRel;
import com.idcos.enterprise.jooq.tables.PortalPermission;
import com.idcos.enterprise.jooq.tables.PortalResource;
import com.idcos.enterprise.jooq.tables.PortalRole;
import com.idcos.enterprise.jooq.tables.PortalSysDict;
import com.idcos.enterprise.jooq.tables.PortalTenant;
import com.idcos.enterprise.jooq.tables.PortalToken;
import com.idcos.enterprise.jooq.tables.PortalUser;
import com.idcos.enterprise.jooq.tables.PortalUserGroup;
import com.idcos.enterprise.jooq.tables.records.PortalDeptRecord;
import com.idcos.enterprise.jooq.tables.records.PortalDeptRoleRelRecord;
import com.idcos.enterprise.jooq.tables.records.PortalGroupRoleRelRecord;
import com.idcos.enterprise.jooq.tables.records.PortalPermissionRecord;
import com.idcos.enterprise.jooq.tables.records.PortalResourceRecord;
import com.idcos.enterprise.jooq.tables.records.PortalRoleRecord;
import com.idcos.enterprise.jooq.tables.records.PortalSysDictRecord;
import com.idcos.enterprise.jooq.tables.records.PortalTenantRecord;
import com.idcos.enterprise.jooq.tables.records.PortalTokenRecord;
import com.idcos.enterprise.jooq.tables.records.PortalUserGroupRecord;
import com.idcos.enterprise.jooq.tables.records.PortalUserRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>clouduam</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<PortalDeptRecord> KEY_PORTAL_DEPT_PRIMARY = UniqueKeys0.KEY_PORTAL_DEPT_PRIMARY;
	public static final UniqueKey<PortalDeptRoleRelRecord> KEY_PORTAL_DEPT_ROLE_REL_PRIMARY = UniqueKeys0.KEY_PORTAL_DEPT_ROLE_REL_PRIMARY;
	public static final UniqueKey<PortalGroupRoleRelRecord> KEY_PORTAL_GROUP_ROLE_REL_PRIMARY = UniqueKeys0.KEY_PORTAL_GROUP_ROLE_REL_PRIMARY;
	public static final UniqueKey<PortalPermissionRecord> KEY_PORTAL_PERMISSION_PRIMARY = UniqueKeys0.KEY_PORTAL_PERMISSION_PRIMARY;
	public static final UniqueKey<PortalResourceRecord> KEY_PORTAL_RESOURCE_PRIMARY = UniqueKeys0.KEY_PORTAL_RESOURCE_PRIMARY;
	public static final UniqueKey<PortalRoleRecord> KEY_PORTAL_ROLE_PRIMARY = UniqueKeys0.KEY_PORTAL_ROLE_PRIMARY;
	public static final UniqueKey<PortalSysDictRecord> KEY_PORTAL_SYS_DICT_PRIMARY = UniqueKeys0.KEY_PORTAL_SYS_DICT_PRIMARY;
	public static final UniqueKey<PortalTenantRecord> KEY_PORTAL_TENANT_PRIMARY = UniqueKeys0.KEY_PORTAL_TENANT_PRIMARY;
	public static final UniqueKey<PortalTokenRecord> KEY_PORTAL_TOKEN_PRIMARY = UniqueKeys0.KEY_PORTAL_TOKEN_PRIMARY;
	public static final UniqueKey<PortalUserRecord> KEY_PORTAL_USER_PRIMARY = UniqueKeys0.KEY_PORTAL_USER_PRIMARY;
	public static final UniqueKey<PortalUserGroupRecord> KEY_PORTAL_USER_GROUP_PRIMARY = UniqueKeys0.KEY_PORTAL_USER_GROUP_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<PortalDeptRecord> KEY_PORTAL_DEPT_PRIMARY = createUniqueKey(PortalDept.PORTAL_DEPT, PortalDept.PORTAL_DEPT.ID);
		public static final UniqueKey<PortalDeptRoleRelRecord> KEY_PORTAL_DEPT_ROLE_REL_PRIMARY = createUniqueKey(PortalDeptRoleRel.PORTAL_DEPT_ROLE_REL, PortalDeptRoleRel.PORTAL_DEPT_ROLE_REL.ID);
		public static final UniqueKey<PortalGroupRoleRelRecord> KEY_PORTAL_GROUP_ROLE_REL_PRIMARY = createUniqueKey(PortalGroupRoleRel.PORTAL_GROUP_ROLE_REL, PortalGroupRoleRel.PORTAL_GROUP_ROLE_REL.ID);
		public static final UniqueKey<PortalPermissionRecord> KEY_PORTAL_PERMISSION_PRIMARY = createUniqueKey(PortalPermission.PORTAL_PERMISSION, PortalPermission.PORTAL_PERMISSION.ID);
		public static final UniqueKey<PortalResourceRecord> KEY_PORTAL_RESOURCE_PRIMARY = createUniqueKey(PortalResource.PORTAL_RESOURCE, PortalResource.PORTAL_RESOURCE.ID);
		public static final UniqueKey<PortalRoleRecord> KEY_PORTAL_ROLE_PRIMARY = createUniqueKey(PortalRole.PORTAL_ROLE, PortalRole.PORTAL_ROLE.ID);
		public static final UniqueKey<PortalSysDictRecord> KEY_PORTAL_SYS_DICT_PRIMARY = createUniqueKey(PortalSysDict.PORTAL_SYS_DICT, PortalSysDict.PORTAL_SYS_DICT.TENANT_ID, PortalSysDict.PORTAL_SYS_DICT.CODE, PortalSysDict.PORTAL_SYS_DICT.TYPE_CODE);
		public static final UniqueKey<PortalTenantRecord> KEY_PORTAL_TENANT_PRIMARY = createUniqueKey(PortalTenant.PORTAL_TENANT, PortalTenant.PORTAL_TENANT.ID);
		public static final UniqueKey<PortalTokenRecord> KEY_PORTAL_TOKEN_PRIMARY = createUniqueKey(PortalToken.PORTAL_TOKEN, PortalToken.PORTAL_TOKEN.ID);
		public static final UniqueKey<PortalUserRecord> KEY_PORTAL_USER_PRIMARY = createUniqueKey(PortalUser.PORTAL_USER, PortalUser.PORTAL_USER.ID);
		public static final UniqueKey<PortalUserGroupRecord> KEY_PORTAL_USER_GROUP_PRIMARY = createUniqueKey(PortalUserGroup.PORTAL_USER_GROUP, PortalUserGroup.PORTAL_USER_GROUP.ID);
	}
}
