/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables.records;


import com.idcos.enterprise.jooq.tables.PortalPermission;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 授权信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalPermissionRecord extends UpdatableRecordImpl<PortalPermissionRecord> implements Record8<String, String, String, String, String, String, String, String> {

	private static final long serialVersionUID = -43383838;

	/**
	 * Setter for <code>clouduam.PORTAL_PERMISSION.ID</code>. 授权信息ID
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_PERMISSION.ID</code>. 授权信息ID
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_PERMISSION.APP_ID</code>. 应用系统名称
	 */
	public void setAppId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_PERMISSION.APP_ID</code>. 应用系统名称
	 */
	public String getAppId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_PERMISSION.AUTH_RES_TYPE</code>. 权限资源类型
	 */
	public void setAuthResType(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_PERMISSION.AUTH_RES_TYPE</code>. 权限资源类型
	 */
	public String getAuthResType() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_PERMISSION.AUTH_RES_ID</code>. 权限资源ID
	 */
	public void setAuthResId(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_PERMISSION.AUTH_RES_ID</code>. 权限资源ID
	 */
	public String getAuthResId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_PERMISSION.AUTH_RES_NAME</code>.
	 */
	public void setAuthResName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_PERMISSION.AUTH_RES_NAME</code>.
	 */
	public String getAuthResName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_PERMISSION.AUTH_OBJ_ID</code>. 授权对象ID
	 */
	public void setAuthObjId(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_PERMISSION.AUTH_OBJ_ID</code>. 授权对象ID
	 */
	public String getAuthObjId() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_PERMISSION.AUTH_OBJ_TYPE</code>. 授权对象类型
	 */
	public void setAuthObjType(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_PERMISSION.AUTH_OBJ_TYPE</code>. 授权对象类型
	 */
	public String getAuthObjType() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_PERMISSION.TENANT</code>. 租户code
	 */
	public void setTenant(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_PERMISSION.TENANT</code>. 租户code
	 */
	public String getTenant() {
		return (String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, String, String, String, String, String, String, String> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, String, String, String, String, String, String, String> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return PortalPermission.PORTAL_PERMISSION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PortalPermission.PORTAL_PERMISSION.APP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PortalPermission.PORTAL_PERMISSION.AUTH_RES_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return PortalPermission.PORTAL_PERMISSION.AUTH_RES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return PortalPermission.PORTAL_PERMISSION.AUTH_RES_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return PortalPermission.PORTAL_PERMISSION.AUTH_OBJ_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return PortalPermission.PORTAL_PERMISSION.AUTH_OBJ_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return PortalPermission.PORTAL_PERMISSION.TENANT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAppId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAuthResType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAuthResId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getAuthResName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAuthObjId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getAuthObjType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getTenant();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalPermissionRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalPermissionRecord value2(String value) {
		setAppId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalPermissionRecord value3(String value) {
		setAuthResType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalPermissionRecord value4(String value) {
		setAuthResId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalPermissionRecord value5(String value) {
		setAuthResName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalPermissionRecord value6(String value) {
		setAuthObjId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalPermissionRecord value7(String value) {
		setAuthObjType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalPermissionRecord value8(String value) {
		setTenant(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalPermissionRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PortalPermissionRecord
	 */
	public PortalPermissionRecord() {
		super(PortalPermission.PORTAL_PERMISSION);
	}

	/**
	 * Create a detached, initialised PortalPermissionRecord
	 */
	public PortalPermissionRecord(String id, String appId, String authResType, String authResId, String authResName, String authObjId, String authObjType, String tenant) {
		super(PortalPermission.PORTAL_PERMISSION);

		setValue(0, id);
		setValue(1, appId);
		setValue(2, authResType);
		setValue(3, authResId);
		setValue(4, authResName);
		setValue(5, authObjId);
		setValue(6, authObjType);
		setValue(7, tenant);
	}
}
