/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables.records;


import com.idcos.enterprise.jooq.tables.PortalUser;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalUserRecord extends UpdatableRecordImpl<PortalUserRecord> {

	private static final long serialVersionUID = -666963976;

	/**
	 * Setter for <code>clouduam.PORTAL_USER.ID</code>. 用户ID
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.ID</code>. 用户ID
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.NAME</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.NAME</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.LOGIN_ID</code>. 登录名
	 */
	public void setLoginId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.LOGIN_ID</code>. 登录名
	 */
	public String getLoginId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.DEPT_ID</code>. 部门id
	 */
	public void setDeptId(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.DEPT_ID</code>. 部门id
	 */
	public String getDeptId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.TITLE</code>. 标签
	 */
	public void setTitle(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.TITLE</code>. 标签
	 */
	public String getTitle() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.MOBILE1</code>.
	 */
	public void setMobile1(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.MOBILE1</code>.
	 */
	public String getMobile1() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.WEIXIN</code>. 标签
	 */
	public void setWeixin(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.WEIXIN</code>. 标签
	 */
	public String getWeixin() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.EMAIL</code>. 邮箱
	 */
	public void setEmail(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.EMAIL</code>. 邮箱
	 */
	public String getEmail() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.IS_ACTIVE</code>. 是否有效
	 */
	public void setIsActive(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.IS_ACTIVE</code>. 是否有效
	 */
	public String getIsActive() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.STATUS</code>. 用户类型：INIT、ENABLED、DISABLED、LOCKED
	 */
	public void setStatus(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.STATUS</code>. 用户类型：INIT、ENABLED、DISABLED、LOCKED
	 */
	public String getStatus() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.REMARK</code>. 备注
	 */
	public void setRemark(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.REMARK</code>. 备注
	 */
	public String getRemark() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.TENANT_ID</code>. 租户编码
	 */
	public void setTenantId(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.TENANT_ID</code>. 租户编码
	 */
	public String getTenantId() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.SOURCE_TYPE</code>. 数据同步来源来源，默认值native表示本系统，如果来自第三方，则需重新定义该值
	 */
	public void setSourceType(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.SOURCE_TYPE</code>. 数据同步来源来源，默认值native表示本系统，如果来自第三方，则需重新定义该值
	 */
	public String getSourceType() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.LAST_MODIFIED_TIME</code>. 最后登录时间
	 */
	public void setLastModifiedTime(Timestamp value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.LAST_MODIFIED_TIME</code>. 最后登录时间
	 */
	public Timestamp getLastModifiedTime() {
		return (Timestamp) getValue(13);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.CREATE_TIME</code>. 创建时间
	 */
	public void setCreateTime(Timestamp value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.CREATE_TIME</code>. 创建时间
	 */
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(14);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.LAST_LOGIN_TIME</code>. 最后修改时间
	 */
	public void setLastLoginTime(Timestamp value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.LAST_LOGIN_TIME</code>. 最后修改时间
	 */
	public Timestamp getLastLoginTime() {
		return (Timestamp) getValue(15);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.PASSWORD</code>. 密码
	 */
	public void setPassword(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.PASSWORD</code>. 密码
	 */
	public String getPassword() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.SALT</code>. 密码盐
	 */
	public void setSalt(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.SALT</code>. 密码盐
	 */
	public String getSalt() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.MOBILE2</code>.
	 */
	public void setMobile2(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.MOBILE2</code>.
	 */
	public String getMobile2() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.RTX</code>. RTX沟通工具
	 */
	public void setRtx(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.RTX</code>. RTX沟通工具
	 */
	public String getRtx() {
		return (String) getValue(19);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.OFFICE_TEL1</code>.
	 */
	public void setOfficeTel1(String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.OFFICE_TEL1</code>.
	 */
	public String getOfficeTel1() {
		return (String) getValue(20);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.OFFICE_TEL2</code>.
	 */
	public void setOfficeTel2(String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.OFFICE_TEL2</code>.
	 */
	public String getOfficeTel2() {
		return (String) getValue(21);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.EMPLOYEE_TYPE</code>.
	 */
	public void setEmployeeType(String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.EMPLOYEE_TYPE</code>.
	 */
	public String getEmployeeType() {
		return (String) getValue(22);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_USER.CREATE_USER</code>. 创建人
	 */
	public void setCreateUser(String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_USER.CREATE_USER</code>. 创建人
	 */
	public String getCreateUser() {
		return (String) getValue(23);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PortalUserRecord
	 */
	public PortalUserRecord() {
		super(PortalUser.PORTAL_USER);
	}

	/**
	 * Create a detached, initialised PortalUserRecord
	 */
	public PortalUserRecord(String id, String name, String loginId, String deptId, String title, String mobile1, String weixin, String email, String isActive, String status, String remark, String tenantId, String sourceType, Timestamp lastModifiedTime, Timestamp createTime, Timestamp lastLoginTime, String password, String salt, String mobile2, String rtx, String officeTel1, String officeTel2, String employeeType, String createUser) {
		super(PortalUser.PORTAL_USER);

		setValue(0, id);
		setValue(1, name);
		setValue(2, loginId);
		setValue(3, deptId);
		setValue(4, title);
		setValue(5, mobile1);
		setValue(6, weixin);
		setValue(7, email);
		setValue(8, isActive);
		setValue(9, status);
		setValue(10, remark);
		setValue(11, tenantId);
		setValue(12, sourceType);
		setValue(13, lastModifiedTime);
		setValue(14, createTime);
		setValue(15, lastLoginTime);
		setValue(16, password);
		setValue(17, salt);
		setValue(18, mobile2);
		setValue(19, rtx);
		setValue(20, officeTel1);
		setValue(21, officeTel2);
		setValue(22, employeeType);
		setValue(23, createUser);
	}
}
