/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables.records;


import com.idcos.enterprise.jooq.tables.PortalTenant;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 租户信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalTenantRecord extends UpdatableRecordImpl<PortalTenantRecord> implements Record6<String, String, String, Timestamp, Timestamp, String> {

	private static final long serialVersionUID = -1223984903;

	/**
	 * Setter for <code>clouduam.PORTAL_TENANT.ID</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_TENANT.ID</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_TENANT.NAME</code>. 租户编码
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_TENANT.NAME</code>. 租户编码
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_TENANT.DISPLAY_NAME</code>. 租户名称
	 */
	public void setDisplayName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_TENANT.DISPLAY_NAME</code>. 租户名称
	 */
	public String getDisplayName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_TENANT.GMT_CREATE</code>. 创建日期
	 */
	public void setGmtCreate(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_TENANT.GMT_CREATE</code>. 创建日期
	 */
	public Timestamp getGmtCreate() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_TENANT.GMT_MODIFIED</code>. 修改日期
	 */
	public void setGmtModified(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_TENANT.GMT_MODIFIED</code>. 修改日期
	 */
	public Timestamp getGmtModified() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_TENANT.IS_ACTIVE</code>. 是否可用
	 */
	public void setIsActive(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_TENANT.IS_ACTIVE</code>. 是否可用
	 */
	public String getIsActive() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, String, Timestamp, Timestamp, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, String, Timestamp, Timestamp, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return PortalTenant.PORTAL_TENANT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PortalTenant.PORTAL_TENANT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PortalTenant.PORTAL_TENANT.DISPLAY_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return PortalTenant.PORTAL_TENANT.GMT_CREATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return PortalTenant.PORTAL_TENANT.GMT_MODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return PortalTenant.PORTAL_TENANT.IS_ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDisplayName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getGmtCreate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getGmtModified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getIsActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalTenantRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalTenantRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalTenantRecord value3(String value) {
		setDisplayName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalTenantRecord value4(Timestamp value) {
		setGmtCreate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalTenantRecord value5(Timestamp value) {
		setGmtModified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalTenantRecord value6(String value) {
		setIsActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalTenantRecord values(String value1, String value2, String value3, Timestamp value4, Timestamp value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PortalTenantRecord
	 */
	public PortalTenantRecord() {
		super(PortalTenant.PORTAL_TENANT);
	}

	/**
	 * Create a detached, initialised PortalTenantRecord
	 */
	public PortalTenantRecord(String id, String name, String displayName, Timestamp gmtCreate, Timestamp gmtModified, String isActive) {
		super(PortalTenant.PORTAL_TENANT);

		setValue(0, id);
		setValue(1, name);
		setValue(2, displayName);
		setValue(3, gmtCreate);
		setValue(4, gmtModified);
		setValue(5, isActive);
	}
}
