/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables.records;


import com.idcos.enterprise.jooq.tables.PortalRole;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalRoleRecord extends UpdatableRecordImpl<PortalRoleRecord> implements Record9<String, String, String, String, String, Timestamp, Timestamp, String, String> {

	private static final long serialVersionUID = 205384238;

	/**
	 * Setter for <code>clouduam.PORTAL_ROLE.ID</code>. 角色ID
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_ROLE.ID</code>. 角色ID
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_ROLE.CODE</code>. 角色编码
	 */
	public void setCode(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_ROLE.CODE</code>. 角色编码
	 */
	public String getCode() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_ROLE.NAME</code>. 角色名称
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_ROLE.NAME</code>. 角色名称
	 */
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_ROLE.REMARK</code>. 角色描述
	 */
	public void setRemark(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_ROLE.REMARK</code>. 角色描述
	 */
	public String getRemark() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_ROLE.CREATE_USER</code>. 创建人
	 */
	public void setCreateUser(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_ROLE.CREATE_USER</code>. 创建人
	 */
	public String getCreateUser() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_ROLE.GMT_CREATE</code>. 创建时间
	 */
	public void setGmtCreate(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_ROLE.GMT_CREATE</code>. 创建时间
	 */
	public Timestamp getGmtCreate() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_ROLE.GMT_MODIFIED</code>. 最后修改时间
	 */
	public void setGmtModified(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_ROLE.GMT_MODIFIED</code>. 最后修改时间
	 */
	public Timestamp getGmtModified() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_ROLE.IS_ACTIVE</code>. 是否有效
	 */
	public void setIsActive(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_ROLE.IS_ACTIVE</code>. 是否有效
	 */
	public String getIsActive() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_ROLE.TENANT</code>. 租户code
	 */
	public void setTenant(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_ROLE.TENANT</code>. 租户code
	 */
	public String getTenant() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, String, String, Timestamp, Timestamp, String, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, String, String, Timestamp, Timestamp, String, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return PortalRole.PORTAL_ROLE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PortalRole.PORTAL_ROLE.CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PortalRole.PORTAL_ROLE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return PortalRole.PORTAL_ROLE.REMARK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return PortalRole.PORTAL_ROLE.CREATE_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return PortalRole.PORTAL_ROLE.GMT_CREATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return PortalRole.PORTAL_ROLE.GMT_MODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return PortalRole.PORTAL_ROLE.IS_ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return PortalRole.PORTAL_ROLE.TENANT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getRemark();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getCreateUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getGmtCreate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getGmtModified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getIsActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getTenant();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRoleRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRoleRecord value2(String value) {
		setCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRoleRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRoleRecord value4(String value) {
		setRemark(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRoleRecord value5(String value) {
		setCreateUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRoleRecord value6(Timestamp value) {
		setGmtCreate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRoleRecord value7(Timestamp value) {
		setGmtModified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRoleRecord value8(String value) {
		setIsActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRoleRecord value9(String value) {
		setTenant(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalRoleRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, String value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PortalRoleRecord
	 */
	public PortalRoleRecord() {
		super(PortalRole.PORTAL_ROLE);
	}

	/**
	 * Create a detached, initialised PortalRoleRecord
	 */
	public PortalRoleRecord(String id, String code, String name, String remark, String createUser, Timestamp gmtCreate, Timestamp gmtModified, String isActive, String tenant) {
		super(PortalRole.PORTAL_ROLE);

		setValue(0, id);
		setValue(1, code);
		setValue(2, name);
		setValue(3, remark);
		setValue(4, createUser);
		setValue(5, gmtCreate);
		setValue(6, gmtModified);
		setValue(7, isActive);
		setValue(8, tenant);
	}
}
