/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables.records;


import com.idcos.enterprise.jooq.tables.PortalGroupUserRel;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * 用户组用户关系表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalGroupUserRelRecord extends TableRecordImpl<PortalGroupUserRelRecord> implements Record4<String, String, String, String> {

	private static final long serialVersionUID = 279811932;

	/**
	 * Setter for <code>clouduam.PORTAL_GROUP_USER_REL.ID</code>. 关系ID
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_GROUP_USER_REL.ID</code>. 关系ID
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_GROUP_USER_REL.USER_ID</code>. 用户ID
	 */
	public void setUserId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_GROUP_USER_REL.USER_ID</code>. 用户ID
	 */
	public String getUserId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_GROUP_USER_REL.GROUP_ID</code>. 用户组ID
	 */
	public void setGroupId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_GROUP_USER_REL.GROUP_ID</code>. 用户组ID
	 */
	public String getGroupId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_GROUP_USER_REL.TENANT</code>. 租户code
	 */
	public void setTenant(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_GROUP_USER_REL.TENANT</code>. 租户code
	 */
	public String getTenant() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, String, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, String, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return PortalGroupUserRel.PORTAL_GROUP_USER_REL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PortalGroupUserRel.PORTAL_GROUP_USER_REL.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PortalGroupUserRel.PORTAL_GROUP_USER_REL.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return PortalGroupUserRel.PORTAL_GROUP_USER_REL.TENANT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getTenant();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalGroupUserRelRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalGroupUserRelRecord value2(String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalGroupUserRelRecord value3(String value) {
		setGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalGroupUserRelRecord value4(String value) {
		setTenant(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalGroupUserRelRecord values(String value1, String value2, String value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PortalGroupUserRelRecord
	 */
	public PortalGroupUserRelRecord() {
		super(PortalGroupUserRel.PORTAL_GROUP_USER_REL);
	}

	/**
	 * Create a detached, initialised PortalGroupUserRelRecord
	 */
	public PortalGroupUserRelRecord(String id, String userId, String groupId, String tenant) {
		super(PortalGroupUserRel.PORTAL_GROUP_USER_REL);

		setValue(0, id);
		setValue(1, userId);
		setValue(2, groupId);
		setValue(3, tenant);
	}
}
