/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables.records;


import com.idcos.enterprise.jooq.tables.PortalDept;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 部门信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalDeptRecord extends UpdatableRecordImpl<PortalDeptRecord> implements Record11<String, String, String, String, String, String, String, String, String, Timestamp, Timestamp> {

	private static final long serialVersionUID = 1423667730;

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.ID</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.ID</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.CODE</code>. 部门code
	 */
	public void setCode(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.CODE</code>. 部门code
	 */
	public String getCode() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.DISPLAY_NAME</code>. 部门名称
	 */
	public void setDisplayName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.DISPLAY_NAME</code>. 部门名称
	 */
	public String getDisplayName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.PARENT_ID</code>. 父项目id
	 */
	public void setParentId(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.PARENT_ID</code>. 父项目id
	 */
	public String getParentId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.STATUS</code>. 部门状态
	 */
	public void setStatus(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.STATUS</code>. 部门状态
	 */
	public String getStatus() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.MANAGER_ID</code>.
	 */
	public void setManagerId(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.MANAGER_ID</code>.
	 */
	public String getManagerId() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.REMARK</code>. 备注
	 */
	public void setRemark(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.REMARK</code>. 备注
	 */
	public String getRemark() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.TENANT_ID</code>. 租户id
	 */
	public void setTenantId(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.TENANT_ID</code>. 租户id
	 */
	public String getTenantId() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.SOURCE_TYPE</code>. 数据同步来源来源，默认值native表示本系统，如果来自第三方，则需重新定义该值
	 */
	public void setSourceType(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.SOURCE_TYPE</code>. 数据同步来源来源，默认值native表示本系统，如果来自第三方，则需重新定义该值
	 */
	public String getSourceType() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.GMT_CREATE</code>. 创建日期
	 */
	public void setGmtCreate(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.GMT_CREATE</code>. 创建日期
	 */
	public Timestamp getGmtCreate() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT.GMT_MODIFIED</code>. 修改日期
	 */
	public void setGmtModified(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT.GMT_MODIFIED</code>. 修改日期
	 */
	public Timestamp getGmtModified() {
		return (Timestamp) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, String, String, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, String, String, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return PortalDept.PORTAL_DEPT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PortalDept.PORTAL_DEPT.CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PortalDept.PORTAL_DEPT.DISPLAY_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return PortalDept.PORTAL_DEPT.PARENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return PortalDept.PORTAL_DEPT.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return PortalDept.PORTAL_DEPT.MANAGER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return PortalDept.PORTAL_DEPT.REMARK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return PortalDept.PORTAL_DEPT.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return PortalDept.PORTAL_DEPT.SOURCE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return PortalDept.PORTAL_DEPT.GMT_CREATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return PortalDept.PORTAL_DEPT.GMT_MODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDisplayName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getParentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getManagerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getRemark();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getSourceType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getGmtCreate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getGmtModified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value2(String value) {
		setCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value3(String value) {
		setDisplayName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value4(String value) {
		setParentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value5(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value6(String value) {
		setManagerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value7(String value) {
		setRemark(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value8(String value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value9(String value) {
		setSourceType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value10(Timestamp value) {
		setGmtCreate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord value11(Timestamp value) {
		setGmtModified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Timestamp value10, Timestamp value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PortalDeptRecord
	 */
	public PortalDeptRecord() {
		super(PortalDept.PORTAL_DEPT);
	}

	/**
	 * Create a detached, initialised PortalDeptRecord
	 */
	public PortalDeptRecord(String id, String code, String displayName, String parentId, String status, String managerId, String remark, String tenantId, String sourceType, Timestamp gmtCreate, Timestamp gmtModified) {
		super(PortalDept.PORTAL_DEPT);

		setValue(0, id);
		setValue(1, code);
		setValue(2, displayName);
		setValue(3, parentId);
		setValue(4, status);
		setValue(5, managerId);
		setValue(6, remark);
		setValue(7, tenantId);
		setValue(8, sourceType);
		setValue(9, gmtCreate);
		setValue(10, gmtModified);
	}
}
