/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables.records;


import com.idcos.enterprise.jooq.tables.PortalSysDict;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * uam系统参数表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalSysDictRecord extends UpdatableRecordImpl<PortalSysDictRecord> implements Record5<String, String, String, String, String> {

	private static final long serialVersionUID = -647030708;

	/**
	 * Setter for <code>clouduam.PORTAL_SYS_DICT.TYPE_CODE</code>. 系统字典类型编码
	 */
	public void setTypeCode(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_SYS_DICT.TYPE_CODE</code>. 系统字典类型编码
	 */
	public String getTypeCode() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_SYS_DICT.CODE</code>. 系统字典编码
	 */
	public void setCode(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_SYS_DICT.CODE</code>. 系统字典编码
	 */
	public String getCode() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_SYS_DICT.VALUE</code>. 参数值
	 */
	public void setValue(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_SYS_DICT.VALUE</code>. 参数值
	 */
	public String getValue() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_SYS_DICT.TENANT_ID</code>. 租户code
	 */
	public void setTenantId(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_SYS_DICT.TENANT_ID</code>. 租户code
	 */
	public String getTenantId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_SYS_DICT.REMARK</code>. 说明
	 */
	public void setRemark(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_SYS_DICT.REMARK</code>. 说明
	 */
	public String getRemark() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<String, String, String> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, String, String, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, String, String, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return PortalSysDict.PORTAL_SYS_DICT.TYPE_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PortalSysDict.PORTAL_SYS_DICT.CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PortalSysDict.PORTAL_SYS_DICT.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return PortalSysDict.PORTAL_SYS_DICT.TENANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return PortalSysDict.PORTAL_SYS_DICT.REMARK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getTypeCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getTenantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getRemark();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalSysDictRecord value1(String value) {
		setTypeCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalSysDictRecord value2(String value) {
		setCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalSysDictRecord value3(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalSysDictRecord value4(String value) {
		setTenantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalSysDictRecord value5(String value) {
		setRemark(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalSysDictRecord values(String value1, String value2, String value3, String value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PortalSysDictRecord
	 */
	public PortalSysDictRecord() {
		super(PortalSysDict.PORTAL_SYS_DICT);
	}

	/**
	 * Create a detached, initialised PortalSysDictRecord
	 */
	public PortalSysDictRecord(String typeCode, String code, String value, String tenantId, String remark) {
		super(PortalSysDict.PORTAL_SYS_DICT);

		setValue(0, typeCode);
		setValue(1, code);
		setValue(2, value);
		setValue(3, tenantId);
		setValue(4, remark);
	}
}
