/**
 * This class is generated by jOOQ
 */
package com.idcos.enterprise.jooq.tables.records;


import com.idcos.enterprise.jooq.tables.PortalDeptRoleRel;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 部门与角色的关系表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalDeptRoleRelRecord extends UpdatableRecordImpl<PortalDeptRoleRelRecord> implements Record3<String, String, String> {

	private static final long serialVersionUID = -673520352;

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT_ROLE_REL.ID</code>. id
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT_ROLE_REL.ID</code>. id
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT_ROLE_REL.DEPT_ID</code>. 部门id
	 */
	public void setDeptId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT_ROLE_REL.DEPT_ID</code>. 部门id
	 */
	public String getDeptId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>clouduam.PORTAL_DEPT_ROLE_REL.ROLE_ID</code>. 角色id
	 */
	public void setRoleId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>clouduam.PORTAL_DEPT_ROLE_REL.ROLE_ID</code>. 角色id
	 */
	public String getRoleId() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return PortalDeptRoleRel.PORTAL_DEPT_ROLE_REL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PortalDeptRoleRel.PORTAL_DEPT_ROLE_REL.DEPT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PortalDeptRoleRel.PORTAL_DEPT_ROLE_REL.ROLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDeptId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getRoleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRoleRelRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRoleRelRecord value2(String value) {
		setDeptId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRoleRelRecord value3(String value) {
		setRoleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalDeptRoleRelRecord values(String value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PortalDeptRoleRelRecord
	 */
	public PortalDeptRoleRelRecord() {
		super(PortalDeptRoleRel.PORTAL_DEPT_ROLE_REL);
	}

	/**
	 * Create a detached, initialised PortalDeptRoleRelRecord
	 */
	public PortalDeptRoleRelRecord(String id, String deptId, String roleId) {
		super(PortalDeptRoleRel.PORTAL_DEPT_ROLE_REL);

		setValue(0, id);
		setValue(1, deptId);
		setValue(2, roleId);
	}
}
